"""
Generator for peer_rank.json — Batch 1 (qualitative peer VERDICT).
Each peer carries a Qual Score /10 and a VERDICT word; the entry adds the
decisive `why`, a best-to-own, a peer-to-avoid and an action. Rerun to rebuild.
Add later batches to DATA and re-run.
"""
import json, os

V_LEADER, V_STRONG, V_SOLID, V_AVG, V_WEAK, V_AVOID = (
    "CLEAR LEADER", "STRONG", "SOLID", "AVERAGE", "WEAK", "AVOID")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "peer_rank.json")


def P(name, score, verdict, self=False):
    d = {"name": name, "score": score, "verdict": verdict}
    if self:
        d["self"] = True
    return d


DATA = {
    "_meta": {
        "description": "PEER VERDICT (qualitative-only) vs the ~6 closest REAL competitors. Each peer carries a Qual Score /10 and a VERDICT word (CLEAR LEADER/STRONG/SOLID/AVERAGE/WEAK/AVOID). self marks the holding; rank = its position; why = decisive factor; plus best-to-own, peer-to-avoid and an action. Separate axis from the portfolio quality score.",
        "verdicts": "CLEAR LEADER | STRONG | SOLID | AVERAGE | WEAK | AVOID",
        "updated": "2026-06-26", "batch": 1,
    },
    "NH": {"set": "Listed hospital chains (India)", "of": 6, "rank": 2, "action": "HOLD",
           "peers": [P("Apollo Hospitals", 8.6, V_LEADER), P("Narayana Hrudayalaya", 8.1, V_STRONG, True), P("Max Healthcare", 8.0, V_STRONG), P("Fortis Healthcare", 7.0, V_SOLID), P("Aster DM Healthcare", 6.4, V_SOLID), P("KIMS (Krishna Institute)", 6.0, V_AVG)],
           "why": "Best capital efficiency and lowest-cost cardiac/oncology delivery; behind only Apollo's scale and pharmacy/diagnostics ecosystem. Cayman drives growth; UK still a margin drag.",
           "best_own": {"name": "Apollo Hospitals", "why": "scale + pharmacy/diagnostics flywheel"}, "avoid": {"name": "KIMS", "why": "rich valuation vs regional concentration"}},
    "HCG": {"set": "Hospital / oncology chains (India)", "of": 6, "rank": 5, "action": "HOLD",
            "peers": [P("Apollo Hospitals", 8.6, V_LEADER), P("Narayana Hrudayalaya", 8.1, V_STRONG), P("Max Healthcare", 8.0, V_STRONG), P("Fortis Healthcare", 7.0, V_SOLID), P("HealthCare Global", 6.8, V_SOLID, True), P("Aster DM Healthcare", 6.4, V_SOLID)],
            "why": "Unmatched dedicated-oncology depth and network, but thin margins, high leverage and ~2% ROE place it behind the diversified majors.",
            "best_own": {"name": "Apollo Hospitals", "why": "diversified high-ROCE compounder"}, "avoid": {"name": "Aster DM Healthcare", "why": "post-merger integration overhang"}},
    "ASTERDM": {"set": "Hospital chains (India)", "of": 6, "rank": 5, "action": "HOLD",
                "peers": [P("Apollo Hospitals", 8.6, V_LEADER), P("Narayana Hrudayalaya", 8.1, V_STRONG), P("Max Healthcare", 8.0, V_STRONG), P("Fortis Healthcare", 7.0, V_SOLID), P("Aster DM Healthcare", 6.4, V_SOLID, True), P("KIMS (Krishna Institute)", 6.0, V_AVG)],
                "why": "Post-GCC India pure-play with improving margins and Kerala brand, but lower ROCE and integration overhang keep it behind Apollo/Max/Fortis.",
                "best_own": {"name": "Max Healthcare", "why": "premium-network margins + RoCE"}, "avoid": {"name": "KIMS", "why": "valuation ahead of fundamentals"}},
    "PARKHOSPS": {"set": "Hospital chains (India)", "of": 6, "rank": 5, "action": "ADD",
                  "peers": [P("Apollo Hospitals", 8.6, V_LEADER), P("Max Healthcare", 8.0, V_STRONG), P("Global Health (Medanta)", 7.6, V_STRONG), P("Fortis Healthcare", 7.0, V_SOLID), P("Park Medi World", 6.6, V_SOLID, True), P("KIMS (Krishna Institute)", 6.0, V_AVG)],
                  "why": "Strong North-India cluster economics, 17% ROE and fast growth, but small scale and high regional concentration vs national majors.",
                  "best_own": {"name": "Max Healthcare", "why": "NCR density + premium ARPOB"}, "avoid": {"name": "KIMS", "why": "regional concentration at premium multiple"}},
    "DATAPATTNS": {"set": "Defence electronics (India)", "of": 6, "rank": 2, "action": "HOLD",
                   "peers": [P("Bharat Electronics (BEL)", 8.5, V_LEADER), P("Data Patterns", 7.8, V_STRONG, True), P("Bharat Dynamics", 7.2, V_SOLID), P("Astra Microwave", 6.9, V_SOLID), P("Paras Defence", 6.3, V_SOLID), P("ideaForge", 5.4, V_WEAK)],
                   "why": "Highest margins and the only fully vertically-integrated (FPGA-to-system) private design house; trails only BEL on scale and order-book, ahead of Paras/ideaForge on profitability.",
                   "best_own": {"name": "Bharat Electronics", "why": "scale, order-book, cash"}, "avoid": {"name": "ideaForge", "why": "loss-making, intense drone competition"}},
    "ASTRAMICRO": {"set": "Defence electronics (India)", "of": 6, "rank": 4, "action": "HOLD",
                   "peers": [P("Bharat Electronics (BEL)", 8.5, V_LEADER), P("Data Patterns", 7.8, V_STRONG), P("Bharat Dynamics", 7.2, V_SOLID), P("Astra Microwave", 6.9, V_SOLID, True), P("Paras Defence", 6.3, V_SOLID), P("Centum Electronics", 5.6, V_AVG)],
                   "why": "Strong RF/microwave franchise and exports with deep DRDO ties, but lower margins and lumpier order flow than Data Patterns and BEL.",
                   "best_own": {"name": "Bharat Electronics", "why": "best mix of scale and returns"}, "avoid": {"name": "Centum Electronics", "why": "thin margins, lumpy execution"}},
    "MTARTECH": {"set": "Precision / aero-defence engineering (India)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Azad Engineering", 8.0, V_STRONG), P("MTAR Technologies", 7.6, V_STRONG, True), P("Data Patterns", 7.5, V_STRONG), P("Dynamatic Technologies", 6.7, V_SOLID), P("Unimech Aerospace", 6.5, V_SOLID), P("Paras Defence", 6.3, V_SOLID)],
                 "why": "Elite micron-tolerance work across nuclear/space/clean-energy; behind Azad on margins and customer diversification. Bloom Energy concentration the key risk.",
                 "best_own": {"name": "Azad Engineering", "why": "higher margins + diversified aero customers"}, "avoid": {"name": "Paras Defence", "why": "execution / order-conversion risk"}},
    "AVANTEL": {"set": "Defence electronics (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Bharat Electronics (BEL)", 8.5, V_LEADER), P("Data Patterns", 7.8, V_STRONG), P("Astra Microwave", 6.9, V_SOLID), P("Avantel", 6.2, V_AVG, True), P("Paras Defence", 6.0, V_AVG), P("Centum Electronics", 5.5, V_WEAK)],
                "why": "Niche Navy satcom/software-defined-radio with high margins, but very small scale and single-customer lumpiness cap overall quality.",
                "best_own": {"name": "Bharat Electronics", "why": "scale + diversified order-book"}, "avoid": {"name": "Centum Electronics", "why": "weak margins, lumpy revenue"}},
    "CYIENTDLM": {"set": "Defence / aerospace EMS (India)", "of": 6, "rank": 4, "action": "HOLD",
                  "peers": [P("Data Patterns", 7.8, V_STRONG), P("Kaynes Technology", 7.6, V_STRONG), P("Syrma SGS", 6.8, V_SOLID), P("Cyient DLM", 6.4, V_SOLID, True), P("Avalon Technologies", 6.2, V_AVG), P("Centum Electronics", 5.6, V_AVG)],
                  "why": "Cyient pedigree with AS9100/NADCAP aero edge, but lower ROCE and a recent revenue dip place it behind Kaynes/Syrma.",
                  "best_own": {"name": "Kaynes Technology", "why": "scale + margin + order-book breadth"}, "avoid": {"name": "Centum Electronics", "why": "structurally thin returns"}},
    "NETWEB": {"set": "Server / AI-infra & EMS (India)", "of": 6, "rank": 1, "action": "HOLD",
               "peers": [P("Netweb Technologies", 8.6, V_LEADER, True), P("Dixon Technologies", 7.8, V_STRONG), P("Kaynes Technology", 7.6, V_STRONG), P("Syrma SGS", 6.8, V_SOLID), P("Avalon Technologies", 6.3, V_SOLID), P("VVDN Technologies", 5.8, V_AVG)],
               "why": "Only listed end-to-end AI/HPC OEM with a Class-I government procurement moat and 30%+ ROE — top of its niche. Rich valuation the sole knock.",
               "best_own": {"name": "Netweb Technologies", "why": "unique moat; add on valuation cooling"}, "avoid": {"name": "VVDN Technologies", "why": "lower-margin, capital-intensive EMS"}},
    "POWERINDIA": {"set": "Power T&D / grid equipment (India)", "of": 6, "rank": 1, "action": "HOLD",
                   "peers": [P("Hitachi Energy India", 8.7, V_LEADER, True), P("ABB India", 8.3, V_STRONG), P("Siemens", 7.6, V_STRONG), P("CG Power", 7.4, V_STRONG), P("GE Vernova T&D India", 6.8, V_SOLID), P("Schneider Electric", 6.5, V_SOLID)],
                   "why": "Near-exclusive HVDC franchise for India's renewable-grid build-out, fastest order-book growth and 21% ROE. Premium valuation the only knock.",
                   "best_own": {"name": "ABB India", "why": "broader automation mix at high RoCE"}, "avoid": {"name": "Schneider Electric", "why": "weaker disclosure/returns vs listed peers"}},
    "HBLENGINE": {"set": "Rail safety & specialised batteries (India)", "of": 6, "rank": 1, "action": "HOLD",
                  "peers": [P("HBL Engineering", 8.4, V_LEADER, True), P("Siemens Mobility", 7.8, V_STRONG), P("Medha Servo (unlisted)", 7.0, V_SOLID), P("Amara Raja Energy", 6.8, V_SOLID), P("Exide Industries", 6.5, V_SOLID), P("Kernex Microsystems", 6.0, V_AVG)],
                  "why": "Primary Kavach ATP supplier with a widening regulatory moat and stand-out 44% ROE; execution pace tied to the Railway budget.",
                  "best_own": {"name": "HBL Engineering", "why": "Kavach moat + best-in-class ROE"}, "avoid": {"name": "Kernex Microsystems", "why": "sub-scale, inconsistent execution"}},
    "SIEMENS": {"set": "Automation & electrical equipment (India)", "of": 6, "rank": 2, "action": "HOLD",
                "peers": [P("ABB India", 8.3, V_LEADER), P("Siemens", 7.6, V_STRONG, True), P("CG Power", 7.4, V_STRONG), P("Larsen & Toubro", 7.2, V_SOLID), P("Rockwell Automation", 7.0, V_SOLID), P("Schneider Electric", 6.8, V_SOLID)],
                "why": "Broad automation + rail + energy franchise and brand trust, but ROCE trails ABB and the energy-business demerger is an overhang.",
                "best_own": {"name": "ABB India", "why": "higher RoCE, cleaner pure-play"}, "avoid": {"name": "Schneider Electric", "why": "weaker disclosure/returns"}},
    "THERMAX": {"set": "Industrial energy & environment (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Cummins India", 7.8, V_STRONG), P("Triveni Turbine", 7.6, V_STRONG), P("Thermax", 7.5, V_STRONG, True), P("Forbes Marshall (unlisted)", 7.0, V_SOLID), P("ISGEC Heavy Engineering", 6.4, V_SOLID), P("BHEL", 5.5, V_WEAK)],
                "why": "Integrated energy + environment solutions leader riding the capex cycle; EPC execution risk and cyclicality vs product-heavy peers keep it just behind.",
                "best_own": {"name": "Cummins India", "why": "product-led, high-RoCE, strong cash"}, "avoid": {"name": "BHEL", "why": "weak returns, execution and PSU drag"}},
    "TRITURBINE": {"set": "Industrial steam turbines (global niche)", "of": 6, "rank": 1, "action": "HOLD",
                   "peers": [P("Triveni Turbine", 8.2, V_LEADER, True), P("Siemens Energy", 7.4, V_STRONG), P("Elliott Group", 6.8, V_SOLID), P("Shin Nippon Machinery", 6.5, V_SOLID), P("Maan Energy", 5.8, V_AVG), P("BHEL", 5.5, V_WEAK)],
                   "why": "Global #2 in sub-100MW industrial turbines with ~26% ROE, dominant after-market and export momentum — best-in-class within its niche.",
                   "best_own": {"name": "Triveni Turbine", "why": "niche leadership + high RoCE"}, "avoid": {"name": "BHEL", "why": "weak returns, heavy-power overhang"}},
    "ELGIEQUIP": {"set": "Air compressors (global)", "of": 6, "rank": 2, "action": "HOLD",
                  "peers": [P("Atlas Copco", 8.6, V_LEADER), P("Elgi Equipment", 7.5, V_STRONG, True), P("Ingersoll Rand India", 7.2, V_SOLID), P("Kaeser", 7.0, V_SOLID), P("Kirloskar Pneumatic", 6.8, V_SOLID), P("Sullair / Hitachi", 6.4, V_SOLID)],
                  "why": "#2 global compressor brand with oil-free IP and 21% ROE; trails only Atlas Copco on scale, ahead of Ingersoll/Kirloskar on technology and reach.",
                  "best_own": {"name": "Atlas Copco", "why": "global scale + best margins"}, "avoid": {"name": "Sullair / Hitachi", "why": "weaker India franchise"}},
    "INOXINDIA": {"set": "Cryogenic equipment (India / global)", "of": 6, "rank": 1, "action": "HOLD",
                  "peers": [P("INOX India", 8.2, V_LEADER, True), P("Linde India", 7.8, V_STRONG), P("Chart Industries", 7.6, V_STRONG), P("Air Liquide", 7.4, V_STRONG), P("Cryofab", 6.0, V_AVG), P("Cryolor", 5.8, V_AVG)],
                  "why": "Only full-stack Indian cryogenic OEM with 26% ROE and LNG/hydrogen/space optionality; dominates the listed peer set.",
                  "best_own": {"name": "INOX India", "why": "domestic monopoly + high RoCE"}, "avoid": {"name": "Cryolor", "why": "sub-scale, narrow franchise"}},
    "NEULANDLAB": {"set": "CDMO / API (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Divi's Laboratories", 8.6, V_LEADER), P("Laurus Labs", 7.6, V_STRONG), P("Neuland Laboratories", 7.5, V_STRONG, True), P("Anthem Biosciences", 7.4, V_STRONG), P("Suven Pharma", 7.2, V_SOLID), P("Sai Life Sciences", 6.8, V_SOLID)],
                   "why": "Rare peptide/GLP-1 plus custom-manufacturing franchise compounding fast; behind Divi's/Laurus on scale, ahead of most on growth. Client concentration the risk.",
                   "best_own": {"name": "Divi's Laboratories", "why": "scale, cost-leadership, balance sheet"}, "avoid": {"name": "Sai Life Sciences", "why": "lower margins, newer track record"}},
    "SUVEN": {"set": "CDMO / specialty pharma (India)", "of": 6, "rank": 4, "action": "HOLD",
              "peers": [P("Divi's Laboratories", 8.6, V_LEADER), P("Laurus Labs", 7.6, V_STRONG), P("Neuland Laboratories", 7.5, V_STRONG), P("Suven Life Sciences", 7.2, V_SOLID, True), P("Cohance Lifesciences", 6.8, V_SOLID), P("Sai Life Sciences", 6.8, V_SOLID)],
              "why": "High-margin CNS-focused CDMO with sticky innovator relationships, but smaller scale and lumpier order flow than Divi's/Neuland.",
              "best_own": {"name": "Divi's Laboratories", "why": "scale + cost leadership"}, "avoid": {"name": "Sai Life Sciences", "why": "thinner margins"}},
    "BIOCON": {"set": "Biopharma / large generics (India)", "of": 6, "rank": 6, "action": "HOLD",
               "peers": [P("Sun Pharma", 8.4, V_LEADER), P("Dr Reddy's", 7.8, V_STRONG), P("Cipla", 7.6, V_STRONG), P("Zydus Lifesciences", 7.0, V_SOLID), P("Lupin", 6.8, V_SOLID), P("Biocon", 6.0, V_AVG, True)],
               "why": "Global biosimilar pioneer (insulins, mAbs), but weak consolidated ROE, leverage and Viatris-integration complexity drag quality below the large generics.",
               "best_own": {"name": "Sun Pharma", "why": "specialty franchise + best returns"}, "avoid": {"name": "Biocon", "why": "leverage + low ROE until biosimilars scale"}},
    "SHILPAMED": {"set": "Oncology API / specialty pharma (India)", "of": 6, "rank": 6, "action": "HOLD",
                  "peers": [P("Divi's Laboratories", 8.6, V_LEADER), P("Laurus Labs", 7.6, V_STRONG), P("Neuland Laboratories", 7.5, V_STRONG), P("Gland Pharma", 7.2, V_SOLID), P("Natco Pharma", 7.0, V_SOLID), P("Shilpa Medicare", 6.2, V_AVG, True)],
                  "why": "Strong oncology HPAPI IP and FDA footprint, but revenue concentration and modest ROE keep it mid-pack versus Divi's/Laurus.",
                  "best_own": {"name": "Divi's Laboratories", "why": "scale + cost leadership"}, "avoid": {"name": "Shilpa Medicare", "why": "concentration + modest returns"}},
    "SANSERA": {"set": "Precision forged auto components (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Bharat Forge", 7.8, V_STRONG), P("Sundram Fasteners", 7.6, V_STRONG), P("Sansera Engineering", 7.2, V_SOLID, True), P("Happy Forgings", 7.0, V_SOLID), P("Ramkrishna Forgings", 6.8, V_SOLID), P("MM Forgings", 6.2, V_AVG)],
                "why": "Diversified precision forgings with aero/defence and EV-agnostic push and very high PAT growth; trails Bharat Forge/Sundram on scale and returns.",
                "best_own": {"name": "Bharat Forge", "why": "scale + defence/export optionality"}, "avoid": {"name": "MM Forgings", "why": "cyclical, lower returns"}},
    "SONACOMS": {"set": "EV-exposed auto components (India)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Uno Minda", 7.8, V_STRONG), P("Bosch India", 7.6, V_STRONG), P("Sundram Fasteners", 7.6, V_STRONG), P("Sona BLW Precision", 7.5, V_STRONG, True), P("Schaeffler India", 7.4, V_STRONG), P("Endurance Technologies", 7.0, V_SOLID)],
                 "why": "Best EV-traction-motor exposure and platform-level switching-cost moat with strong order book; margin compression vs revenue growth the watch-item.",
                 "best_own": {"name": "Uno Minda", "why": "diversified, consistent compounding"}, "avoid": {"name": "Endurance Technologies", "why": "more ICE-tied mix"}},
    "SKFINDIA": {"set": "Bearings (India)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Schaeffler India", 7.8, V_STRONG), P("SKF India", 7.4, V_STRONG, True), P("Timken India", 7.2, V_SOLID), P("AB SKF (global)", 7.0, V_SOLID), P("NRB Bearings", 6.4, V_SOLID), P("NEI / Tata Bearings", 6.0, V_AVG)],
                 "why": "Top-2 bearing maker with strong after-market and ~29% ROE; Schaeffler edges ahead on breadth and EV-drivetrain content.",
                 "best_own": {"name": "Schaeffler India", "why": "broadest portfolio + EV content"}, "avoid": {"name": "NEI / Tata Bearings", "why": "sub-scale, lower returns"}},
    "KPITTECH": {"set": "Automotive software / ER&D (India)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Tata Elxsi", 7.8, V_STRONG), P("KPIT Technologies", 7.3, V_STRONG, True), P("L&T Technology Services", 7.2, V_SOLID), P("Persistent Systems", 7.0, V_SOLID), P("Tata Technologies", 6.8, V_SOLID), P("Cyient", 6.4, V_SOLID)],
                 "why": "Pure-play software-defined-vehicle specialist with deep OEM lock-in and 19 straight growth quarters; recent PAT dip and customer concentration the risks.",
                 "best_own": {"name": "Tata Elxsi", "why": "higher margins, design-led moat"}, "avoid": {"name": "Cyient", "why": "slower growth, broader mix"}},
    "AFFLE": {"set": "AdTech / digital marketing (India + global)", "of": 6, "rank": 3, "action": "HOLD",
              "peers": [P("The Trade Desk", 8.2, V_LEADER), P("AppLovin", 8.0, V_STRONG), P("Affle India", 7.6, V_STRONG, True), P("InMobi (unlisted)", 6.8, V_SOLID), P("Latent View (adjacent)", 6.6, V_SOLID), P("Brightcom Group", 3.0, V_AVOID)],
              "why": "India's #1 mobile ad-tech with a 3bn-device-profile data moat and conversion-based CPCU model; leads listed India, though global majors out-scale it.",
              "best_own": {"name": "Affle India", "why": "India leadership + data moat"}, "avoid": {"name": "Brightcom Group", "why": "serious governance/accounting red flags"}},
    "RATEGAIN": {"set": "Travel / hospitality SaaS (global)", "of": 6, "rank": 3, "action": "HOLD",
                 "peers": [P("Amadeus", 8.2, V_LEADER), P("IDeaS (SAS)", 7.4, V_STRONG), P("RateGain", 7.3, V_STRONG, True), P("Duetto", 6.6, V_SOLID), P("Cloudbeds", 6.2, V_AVG), P("Sabre", 6.0, V_AVG)],
                 "why": "Largest India-listed travel-tech SaaS with rate-shopping data network effects and 700+ integrations; leads listed India, competes globally with IDeaS/Duetto.",
                 "best_own": {"name": "RateGain", "why": "only listed-India pure-play with data moat"}, "avoid": {"name": "Sabre", "why": "high leverage, structural pressure"}},
    "MAPMYINDIA": {"set": "Maps / location-tech (India)", "of": 6, "rank": 2, "action": "HOLD",
                   "peers": [P("Google Maps (unlisted)", 9.0, V_LEADER), P("MapmyIndia", 7.6, V_STRONG, True), P("HERE Technologies", 6.6, V_SOLID), P("Genesys International", 6.4, V_SOLID), P("TomTom", 5.8, V_AVG), P("Ola Maps (unlisted)", 5.5, V_WEAK)],
                   "why": "Only profitable Indian maps + location platform with a 30-year sovereign-data moat and 15% ROE; dominant among listed India, faces Google on the consumer side.",
                   "best_own": {"name": "MapmyIndia", "why": "sovereign-data moat + profitability"}, "avoid": {"name": "Ola Maps (unlisted)", "why": "unproven, cash-burning challenger"}},
    "TATACOMM": {"set": "Enterprise telecom / data networking (India)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Bharti Airtel", 8.4, V_LEADER), P("Tata Communications", 7.2, V_SOLID, True), P("Route Mobile", 6.4, V_SOLID), P("Sify Technologies", 6.0, V_AVG), P("Lumen (global)", 4.5, V_WEAK), P("Vodafone Idea", 3.5, V_AVOID)],
                 "why": "Owns a global submarine-cable backbone with an enterprise/NaaS moat; high leverage and slower growth keep it behind Airtel on overall quality.",
                 "best_own": {"name": "Bharti Airtel", "why": "best returns + balance-sheet repair"}, "avoid": {"name": "Vodafone Idea", "why": "balance-sheet distress, survival risk"}},
    "INDUSTOWER": {"set": "Telecom towers (India)", "of": 6, "rank": 1, "action": "HOLD",
                   "peers": [P("Indus Towers", 7.4, V_STRONG, True), P("Summit Digitel (Brookfield)", 7.2, V_SOLID), P("ATC India (American Tower)", 7.0, V_SOLID), P("Bharti Infratel (merged)", 7.0, V_SOLID), P("Tower Vision", 5.5, V_WEAK), P("GTL Infrastructure", 3.5, V_AVOID)],
                   "why": "Largest Indian towerco with 19.8% ROE and 226k towers; Vodafone-Idea receivables are the swing factor on quality.",
                   "best_own": {"name": "Indus Towers", "why": "scale + ROE; VIL recovery optionality"}, "avoid": {"name": "GTL Infrastructure", "why": "chronic losses, debt distress"}},
    "RAILTEL": {"set": "Telecom infra / data PSUs (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Tata Communications", 7.2, V_SOLID), P("Tejas Networks", 7.0, V_SOLID), P("RailTel", 6.8, V_SOLID, True), P("HFCL", 6.0, V_AVG), P("Sterlite Technologies", 5.8, V_AVG), P("ITI Limited", 4.5, V_WEAK)],
                "why": "Exclusive rail-track optic-fibre and data-centre push with 16% ROE and a clean balance sheet; PSU execution pace caps the re-rating.",
                "best_own": {"name": "Tata Communications", "why": "global backbone + enterprise moat"}, "avoid": {"name": "ITI Limited", "why": "loss-making, weak execution"}},
    "GMRAIRPORT": {"set": "Airport operators (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Bangalore Int'l Airport (unlisted)", 7.4, V_STRONG), P("Adani Airports (unlisted)", 7.2, V_SOLID), P("GMR Airports", 7.0, V_SOLID, True), P("Cochin Int'l Airport", 6.6, V_SOLID), P("AAI (govt)", 5.5, V_WEAK), P("GVK (defunct)", 2.5, V_AVOID)],
                   "why": "Operates Delhi + Hyderabad 60-year concessions — natural monopolies with strong traffic CAGR; high infra leverage is the only real knock.",
                   "best_own": {"name": "GMR Airports", "why": "only listed pure-play airport monopoly"}, "avoid": {"name": "GVK (defunct)", "why": "collapsed under debt; cautionary tale"}},
    "CARBORUNIV": {"set": "Abrasives & ceramics (India)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Saint-Gobain (global)", 7.8, V_STRONG), P("AIA Engineering (adjacent)", 7.6, V_STRONG), P("Grindwell Norton", 7.4, V_STRONG), P("3M India", 7.2, V_SOLID), P("Carborundum Universal", 7.0, V_SOLID, True), P("Wendt India", 6.4, V_SOLID)],
                   "why": "Full-stack abrasives-to-electro-minerals (SiC) franchise with Murugappa backing; recent low ROE/high PE let Grindwell edge ahead on returns.",
                   "best_own": {"name": "Grindwell Norton", "why": "higher RoCE, cleaner returns"}, "avoid": {"name": "Wendt India", "why": "illiquid, recent earnings decline"}},
    "GRINDWELL": {"set": "Abrasives & ceramics (India)", "of": 6, "rank": 3, "action": "HOLD",
                  "peers": [P("Saint-Gobain (global)", 7.8, V_STRONG), P("AIA Engineering (adjacent)", 7.6, V_STRONG), P("Grindwell Norton", 7.4, V_STRONG, True), P("3M India", 7.2, V_SOLID), P("Carborundum Universal", 7.0, V_SOLID), P("Wendt India", 6.4, V_SOLID)],
                  "why": "Saint-Gobain technology, 17% ROE and disciplined capital allocation; leads listed-India abrasives on returns and consistency.",
                  "best_own": {"name": "Grindwell Norton", "why": "best returns + parent tech access"}, "avoid": {"name": "Wendt India", "why": "sub-scale, earnings volatility"}},
    "SYRMA": {"set": "EMS / electronics (India)", "of": 6, "rank": 3, "action": "HOLD",
              "peers": [P("Dixon Technologies", 8.0, V_STRONG), P("Kaynes Technology", 7.8, V_STRONG), P("Syrma SGS", 6.8, V_SOLID, True), P("Cyient DLM", 6.4, V_SOLID), P("Avalon Technologies", 6.3, V_SOLID), P("VVDN Technologies", 5.8, V_AVG)],
              "why": "Design-led EMS with RFID and medical niches, but smaller scale and thinner margins than Dixon/Kaynes.",
              "best_own": {"name": "Dixon Technologies", "why": "scale + execution + ROE"}, "avoid": {"name": "VVDN Technologies", "why": "capital-intensive, lower margin"}},
    "AVALON": {"set": "EMS / electronics (India)", "of": 6, "rank": 5, "action": "HOLD",
               "peers": [P("Dixon Technologies", 8.0, V_STRONG), P("Kaynes Technology", 7.8, V_STRONG), P("Syrma SGS", 6.8, V_SOLID), P("Cyient DLM", 6.4, V_SOLID), P("Avalon Technologies", 6.3, V_SOLID, True), P("Centum Electronics", 5.6, V_AVG)],
               "why": "US-export EMS with clean-energy/medical niche but customer concentration and lower margins.",
               "best_own": {"name": "Dixon Technologies", "why": "scale + ROE"}, "avoid": {"name": "Centum Electronics", "why": "thin, lumpy returns"}},
    "TVSELECT": {"set": "Electronics / IT peripherals (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Dixon Technologies", 8.0, V_STRONG), P("Kaynes Technology", 7.6, V_STRONG), P("Control Print", 6.8, V_SOLID), P("eMudhra", 6.4, V_SOLID), P("TVS Electronics", 5.6, V_AVG, True), P("Posiflex (global)", 6.0, V_AVG)],
                 "why": "TVS-brand POS servicing niche but commoditised peripherals and very low ROE.",
                 "best_own": {"name": "Dixon Technologies", "why": "scale + returns"}, "avoid": {"name": "Posiflex (global)", "why": "commoditised hardware"}},
    "DLINKINDIA": {"set": "Networking hardware (India)", "of": 6, "rank": 4, "action": "HOLD",
                   "peers": [P("Cisco (global)", 8.5, V_LEADER), P("HPE Aruba (global)", 8.0, V_STRONG), P("TP-Link", 7.0, V_SOLID), P("D-Link India", 6.4, V_SOLID, True), P("Netgear", 6.2, V_AVG), P("Tenda", 5.5, V_WEAK)],
                   "why": "Established SMB networking brand with 21% ROE but shallow moat and distribution-led vs Cisco/Aruba.",
                   "best_own": {"name": "Cisco (global)", "why": "enterprise moat + R&D"}, "avoid": {"name": "Tenda", "why": "low-end commoditised"}},
    "MOSCHIP": {"set": "Semiconductors / chip design (India)", "of": 6, "rank": 5, "action": "HOLD",
                "peers": [P("Tata Elxsi", 8.0, V_STRONG), P("L&T Technology Services", 7.4, V_STRONG), P("Cyient", 7.0, V_SOLID), P("Sasken Technologies", 6.4, V_SOLID), P("MosChip Technologies", 6.0, V_AVG, True), P("SPEL Semiconductor", 5.0, V_WEAK)],
                "why": "Pioneering Indian fabless ASIC design with semi-mission tailwind but tiny scale and very high PE.",
                "best_own": {"name": "Tata Elxsi", "why": "scale + margins + design moat"}, "avoid": {"name": "SPEL Semiconductor", "why": "sub-scale, weak returns"}},
    "SASKEN": {"set": "Embedded / chipset software (India)", "of": 6, "rank": 5, "action": "HOLD",
               "peers": [P("Tata Elxsi", 8.0, V_STRONG), P("L&T Technology Services", 7.4, V_STRONG), P("KPIT Technologies", 7.3, V_STRONG), P("Cyient", 7.0, V_SOLID), P("Sasken Technologies", 6.4, V_SOLID, True), P("MosChip Technologies", 6.0, V_AVG)],
               "why": "Deep chipset/modem software ties to Qualcomm/MediaTek but small scale and client concentration.",
               "best_own": {"name": "Tata Elxsi", "why": "margins + design moat"}, "avoid": {"name": "MosChip Technologies", "why": "tiny, high PE"}},
    "RAMCOSYS": {"set": "Enterprise software / ERP (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Oracle Financial Services", 8.0, V_STRONG), P("Intellect Design", 7.4, V_STRONG), P("Newgen Software", 7.2, V_SOLID), P("Nucleus Software", 6.2, V_AVG), P("Ramco Systems", 6.0, V_AVG, True), P("Quick Heal", 5.6, V_AVG)],
                 "why": "Sticky aviation-MRO ERP niche but years of slow growth and inconsistent profitability.",
                 "best_own": {"name": "Intellect Design", "why": "product depth + growth"}, "avoid": {"name": "Quick Heal", "why": "declining core franchise"}},
    "RPTECH": {"set": "IT products distribution (India)", "of": 6, "rank": 2, "action": "HOLD",
               "peers": [P("Redington", 8.0, V_STRONG), P("Rashi Peripherals", 7.0, V_SOLID, True), P("Savex (unlisted)", 6.8, V_SOLID), P("Inflow Technologies", 6.0, V_AVG), P("Supertron", 5.8, V_AVG), P("Compuage", 5.0, V_WEAK)],
               "why": "#2 national IT distributor with NVIDIA/AMD lines; thin distribution margins vs Redington's scale.",
               "best_own": {"name": "Redington", "why": "scale, cloud mix, returns"}, "avoid": {"name": "Compuage", "why": "financial stress / governance"}},
    "REDINGTON": {"set": "IT products distribution (India)", "of": 6, "rank": 1, "action": "HOLD",
                  "peers": [P("Redington", 8.0, V_STRONG, True), P("Rashi Peripherals", 7.0, V_SOLID), P("Savex (unlisted)", 6.8, V_SOLID), P("Inflow Technologies", 6.0, V_AVG), P("Supertron", 5.8, V_AVG), P("Compuage", 5.0, V_WEAK)],
                  "why": "Largest, most-diversified IT distributor with cloud-solutions mix and 13% ROE; leads the set.",
                  "best_own": {"name": "Redington", "why": "scale + cloud + balance sheet"}, "avoid": {"name": "Compuage", "why": "financial stress"}},
    "FRACTAL": {"set": "AI / data analytics (India + global)", "of": 6, "rank": 2, "action": "HOLD",
                "peers": [P("Palantir (global)", 8.4, V_LEADER), P("Fractal Analytics", 7.6, V_STRONG, True), P("Tiger Analytics (unlisted)", 7.0, V_SOLID), P("Latent View", 6.8, V_SOLID), P("Mu Sigma (unlisted)", 6.4, V_SOLID), P("Course5 Intelligence", 6.0, V_AVG)],
                "why": "AI-native Fortune-500 analytics with Qure.ai optionality; leads India peers, behind global Palantir on scale.",
                "best_own": {"name": "Fractal Analytics", "why": "AI-native breadth + clients"}, "avoid": {"name": "Course5 Intelligence", "why": "sub-scale"}},
    "LATENTVIEW": {"set": "Data analytics (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Fractal Analytics", 7.6, V_STRONG), P("Tiger Analytics (unlisted)", 7.0, V_SOLID), P("Latent View", 6.8, V_SOLID, True), P("Mu Sigma (unlisted)", 6.4, V_SOLID), P("Course5 Intelligence", 6.0, V_AVG), P("Affine Analytics", 5.6, V_AVG)],
                   "why": "Profitable pure-play analytics with strong cash but US-tech client concentration and ~12% ROE.",
                   "best_own": {"name": "Fractal Analytics", "why": "scale + AI breadth"}, "avoid": {"name": "Affine Analytics", "why": "sub-scale"}},
    "PROTEAN": {"set": "GovTech / digital public infra (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("CAMS", 8.0, V_STRONG), P("CDSL", 7.8, V_STRONG), P("Protean eGov", 7.6, V_STRONG, True), P("KFin Technologies", 7.4, V_STRONG), P("IRCTC", 7.2, V_SOLID), P("eMudhra", 6.6, V_SOLID)],
                "why": "PAN/NPS monopoly-like franchise but slower growth and lower margins than CAMS/CDSL.",
                "best_own": {"name": "CAMS", "why": "duopoly RTA + best margins"}, "avoid": {"name": "eMudhra", "why": "smaller, competitive niche"}},
    "URBANCO": {"set": "Consumer-services marketplace (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Info Edge", 8.0, V_STRONG), P("Zomato (Eternal)", 7.8, V_STRONG), P("Urban Company", 6.6, V_SOLID, True), P("Justdial", 6.4, V_SOLID), P("Awfis", 6.2, V_AVG), P("FirstCry", 6.0, V_AVG)],
                "why": "Full-stack home-services leader turning profitable but fragmented market and volatile margins.",
                "best_own": {"name": "Info Edge", "why": "durable platform + investments"}, "avoid": {"name": "FirstCry", "why": "competitive, thin margins"}},
    "UNIECOM": {"set": "E-commerce enablement SaaS (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Shopify (global)", 8.4, V_LEADER), P("Zoho (unlisted)", 7.6, V_STRONG), P("Unicommerce", 6.8, V_SOLID, True), P("Vinculum (unlisted)", 6.4, V_SOLID), P("EasyEcom", 6.0, V_AVG), P("Browntape", 5.6, V_AVG)],
                "why": "Profitable SaaS with marketplace integrations and network effects but SMB churn and price competition.",
                "best_own": {"name": "Zoho (unlisted)", "why": "scale + product breadth"}, "avoid": {"name": "Browntape", "why": "sub-scale"}},
    "NIITLTD": {"set": "Skilling / EdTech (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("NIIT Learning Systems", 7.4, V_STRONG), P("Aptech", 6.8, V_SOLID), P("NIIT Limited", 6.0, V_AVG, True), P("CL Educate", 5.8, V_AVG), P("Career Point", 5.6, V_AVG), P("Veranda Learning", 5.4, V_WEAK)],
                "why": "30-year brand and corporate-skilling shift but very low ROE and high PE post Coforge split.",
                "best_own": {"name": "NIIT Learning Systems", "why": "profitable corporate L&D"}, "avoid": {"name": "Veranda Learning", "why": "loss-making, leveraged"}},
    "NEPHROPLUS": {"set": "Dialysis / specialty care (India + Asia)", "of": 6, "rank": 4, "action": "HOLD",
                   "peers": [P("Fresenius (global)", 8.0, V_STRONG), P("DaVita (global)", 8.0, V_STRONG), P("Apollo Dialysis", 7.6, V_STRONG), P("NephroPlus", 7.0, V_SOLID, True), P("B Braun", 6.4, V_SOLID), P("DCDC (unlisted)", 6.0, V_AVG)],
                   "why": "Asia's largest dialysis chain with chronic-patient stickiness and PPP model, but capital-intensive and low ROE.",
                   "best_own": {"name": "Fresenius (global)", "why": "scale + integrated products"}, "avoid": {"name": "DCDC (unlisted)", "why": "sub-scale"}},
    "INDGN": {"set": "Pharma commercialization / CRO (India)", "of": 6, "rank": 4, "action": "HOLD",
              "peers": [P("IQVIA (global)", 8.4, V_LEADER), P("Syneos Health", 7.6, V_STRONG), P("WNS", 7.2, V_SOLID), P("Indegene", 7.0, V_SOLID, True), P("eClerx", 6.6, V_SOLID), P("Firstsource", 6.4, V_SOLID)],
              "why": "Niche life-sciences digital/commercial-ops with top-pharma stickiness but client concentration and a margin dip.",
              "best_own": {"name": "IQVIA (global)", "why": "data + scale moat"}, "avoid": {"name": "Firstsource", "why": "broader, lower-margin BPM"}},
    "YATHARTH": {"set": "Hospital chains (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Apollo Hospitals", 8.6, V_LEADER), P("Max Healthcare", 8.0, V_STRONG), P("Fortis Healthcare", 7.0, V_SOLID), P("Park Medi World", 6.6, V_SOLID), P("Yatharth Hospital", 6.4, V_SOLID, True), P("KIMS (Krishna Institute)", 6.0, V_AVG)],
                 "why": "Fast-growing NCR multi-specialty with improving occupancy but small scale and doctor-attrition risk.",
                 "best_own": {"name": "Max Healthcare", "why": "NCR density + ARPOB"}, "avoid": {"name": "KIMS", "why": "valuation vs concentration"}},
    "VIYASH": {"set": "API / CDMO (India)", "of": 6, "rank": 5, "action": "HOLD",
               "peers": [P("Divi's Laboratories", 8.6, V_LEADER), P("Laurus Labs", 7.6, V_STRONG), P("Neuland Laboratories", 7.5, V_STRONG), P("Aarti Pharmalabs", 7.0, V_SOLID), P("Viyash Scientific", 6.6, V_SOLID, True), P("Solara Active Pharma", 5.8, V_AVG)],
               "why": "Fully backward-integrated API+formulation turnaround with fast growth but recent listing and leverage.",
               "best_own": {"name": "Divi's Laboratories", "why": "scale + cost leadership"}, "avoid": {"name": "Solara Active Pharma", "why": "volatile, stressed history"}},
    "WOCKPHARMA": {"set": "Pharma — innovation / generics (India)", "of": 6, "rank": 6, "action": "HOLD",
                   "peers": [P("Sun Pharma", 8.4, V_LEADER), P("Dr Reddy's", 7.8, V_STRONG), P("Cipla", 7.6, V_STRONG), P("Alkem Laboratories", 7.2, V_SOLID), P("Lupin", 6.8, V_SOLID), P("Wockhardt", 5.8, V_AVG, True)],
                   "why": "Novel anti-infective optionality (Zaynich) but loss-making legacy and high PE; quality trails large peers.",
                   "best_own": {"name": "Sun Pharma", "why": "specialty + best returns"}, "avoid": {"name": "Wockhardt", "why": "await commercialization & profits"}},
    "GAUDIUMIVF": {"set": "Fertility / women's healthcare (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Indira IVF (unlisted)", 8.0, V_STRONG), P("Nova IVF (unlisted)", 7.6, V_STRONG), P("Gaudium IVF", 7.0, V_SOLID, True), P("Apollo Fertility", 6.6, V_SOLID), P("Morpheus", 6.4, V_SOLID), P("Bloom IVF", 6.0, V_AVG)],
                   "why": "High-margin scalable IVF network with trust/referral moat but doctor dependency and newly listed.",
                   "best_own": {"name": "Indira IVF (unlisted)", "why": "scale + brand"}, "avoid": {"name": "Bloom IVF", "why": "sub-scale"}},
    "ENTERO": {"set": "Pharma distribution (India)", "of": 6, "rank": 3, "action": "HOLD",
               "peers": [P("Apollo Pharmacy", 7.6, V_STRONG), P("MedPlus Health", 7.2, V_SOLID), P("Entero Healthcare", 7.0, V_SOLID, True), P("Ascent Health", 6.4, V_SOLID), P("Sanjivani (unlisted)", 6.0, V_AVG), P("PharmEasy (unlisted)", 5.5, V_WEAK)],
               "why": "Tech-enabled B2B pharma-distribution consolidator with route density but thin margins and WC-heavy.",
               "best_own": {"name": "MedPlus Health", "why": "integrated retail + returns"}, "avoid": {"name": "PharmEasy (unlisted)", "why": "cash-burn, governance"}},
    "LAXMIDENTL": {"set": "Dental products (India + global)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Align Technology (global)", 8.4, V_LEADER), P("Straumann (global)", 7.8, V_STRONG), P("Dentsply Sirona", 7.6, V_STRONG), P("Poly Medicure (adjacent)", 7.0, V_SOLID), P("Laxmi Dental", 6.6, V_SOLID, True), P("Local labs", 5.8, V_AVG)],
                   "why": "India's largest dental-products maker with aligner optionality but small scale vs global majors.",
                   "best_own": {"name": "Align Technology (global)", "why": "aligner moat + scale"}, "avoid": {"name": "Local labs", "why": "fragmented, sub-scale"}},
    "RUBICON": {"set": "Specialty pharma / CDMO (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Divi's Laboratories", 8.6, V_LEADER), P("Laurus Labs", 7.6, V_STRONG), P("Rubicon Research", 7.2, V_SOLID, True), P("Gland Pharma", 7.2, V_SOLID), P("Suven Pharma", 7.2, V_SOLID), P("Sai Life Sciences", 6.8, V_SOLID)],
                "why": "Complex drug-delivery CDMO with 27% ROE and fast growth; behind Divi's/Laurus on scale.",
                "best_own": {"name": "Divi's Laboratories", "why": "scale + cost leadership"}, "avoid": {"name": "Sai Life Sciences", "why": "thinner margins"}},
    "BLUEJET": {"set": "Contrast-media / niche CDMO (global)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Divi's Laboratories", 8.6, V_LEADER), P("GE Healthcare (global)", 8.0, V_STRONG), P("Bluejet Healthcare", 7.4, V_STRONG, True), P("Suven Pharma", 7.2, V_SOLID), P("Bracco (unlisted)", 7.0, V_SOLID), P("Guerbet", 6.6, V_SOLID)],
                "why": "One of few global contrast-media intermediate makers with 60% gross margins but customer concentration (GE/Bayer).",
                "best_own": {"name": "Divi's Laboratories", "why": "scale + diversification"}, "avoid": {"name": "Guerbet", "why": "leveraged, slower growth"}},
    "FREDUN": {"set": "Injectable / specialty pharma (India)", "of": 6, "rank": 4, "action": "HOLD",
               "peers": [P("Gland Pharma", 7.6, V_STRONG), P("Caplin Point", 7.4, V_STRONG), P("Marksans Pharma", 6.6, V_SOLID), P("Fredun Pharmaceuticals", 6.4, V_SOLID, True), P("Shilpa Medicare", 6.2, V_AVG), P("Jagsonpal Pharma", 6.0, V_AVG)],
               "why": "Complex-injectables niche with regulated exports but very small scale and FDA-inspection risk.",
               "best_own": {"name": "Caplin Point", "why": "high-ROCE LatAm + injectables"}, "avoid": {"name": "Jagsonpal Pharma", "why": "sub-scale"}},
    "ANURAS": {"set": "Specialty chemicals — custom synthesis (India)", "of": 6, "rank": 6, "action": "HOLD",
               "peers": [P("PI Industries", 8.4, V_LEADER), P("SRF", 8.0, V_STRONG), P("Navin Fluorine", 7.6, V_STRONG), P("Vinati Organics", 7.2, V_SOLID), P("Aarti Industries", 7.0, V_SOLID), P("Anupam Rasayan", 6.6, V_SOLID, True)],
               "why": "Long-term contracted custom-synthesis order book but high debt, working-capital intensity and margin pressure vs leaders.",
               "best_own": {"name": "PI Industries", "why": "best-in-class CSM + returns"}, "avoid": {"name": "Aarti Industries", "why": "commodity-cycle swings"}},
    "STALLION": {"set": "Fluorochemicals / refrigerants (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("SRF", 8.0, V_STRONG), P("Navin Fluorine", 7.6, V_STRONG), P("Gujarat Fluorochemicals", 7.4, V_STRONG), P("Tanfac Industries", 6.6, V_SOLID), P("Stallion India", 6.0, V_AVG, True), P("Amal", 5.6, V_AVG)],
                 "why": "Largest refrigerant-gas importer/distributor but low-margin distribution and price/regulatory risk.",
                 "best_own": {"name": "SRF", "why": "integrated fluorochemicals moat"}, "avoid": {"name": "Amal", "why": "sub-scale commodity"}},
    "GULFOILLUB": {"set": "Lubricants (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Castrol India", 7.8, V_STRONG), P("Shell (unlisted)", 7.6, V_STRONG), P("Gulf Oil Lubricants", 7.2, V_SOLID, True), P("Tide Water (Veedol)", 6.8, V_SOLID), P("Savita Oil", 6.4, V_SOLID), P("GP Petroleums", 6.0, V_AVG)],
                   "why": "#3 lubricant brand with 22% ROE and strong distribution but EV-transition overhang and crude-linked margins.",
                   "best_own": {"name": "Castrol India", "why": "#1 brand + cash returns"}, "avoid": {"name": "GP Petroleums", "why": "sub-scale"}},
    "ASALCBR": {"set": "Alcoholic beverages / ENA (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("United Spirits", 8.2, V_STRONG), P("Radico Khaitan", 7.8, V_STRONG), P("Globus Spirits", 6.8, V_SOLID), P("Associated Alcohols", 6.6, V_SOLID, True), P("Tilaknagar Industries", 6.4, V_SOLID), P("Som Distilleries", 6.0, V_AVG)],
                "why": "Integrated ENA+IMFL+bottling with steady returns but small scale and state-policy exposure.",
                "best_own": {"name": "United Spirits", "why": "premium brands + scale"}, "avoid": {"name": "Som Distilleries", "why": "regional, thin"}},
    "TRIVENI": {"set": "Sugar & ethanol (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Balrampur Chini", 7.8, V_STRONG), P("EID Parry", 7.4, V_STRONG), P("Dalmia Bharat Sugar", 7.2, V_SOLID), P("Triveni Engineering", 7.0, V_SOLID, True), P("Dwarikesh Sugar", 6.4, V_SOLID), P("Bajaj Hindusthan", 5.0, V_WEAK)],
                "why": "Diversified sugar+distillery+engineering with ethanol tailwind but regulated sugar economics.",
                "best_own": {"name": "Balrampur Chini", "why": "best distillery mix + returns"}, "avoid": {"name": "Bajaj Hindusthan", "why": "debt-laden, weak"}},
    "GREAVESCOT": {"set": "Engines & EV powertrain (India)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Bosch India", 8.0, V_STRONG), P("Cummins India", 7.8, V_STRONG), P("Kirloskar Oil Engines", 7.0, V_SOLID), P("Olectra Greentech", 6.4, V_SOLID), P("Greaves Cotton", 6.2, V_AVG, True), P("Ola Electric", 5.6, V_AVG)],
                   "why": "#1 3-wheeler engine plus Ampere EV, but EV losses and ICE decline weigh on overall quality.",
                   "best_own": {"name": "Cummins India", "why": "product-led, high-RoCE"}, "avoid": {"name": "Ola Electric", "why": "cash-burn, competition"}},
    "VSTTILLERS": {"set": "Farm equipment (India)", "of": 6, "rank": 4, "action": "HOLD",
                   "peers": [P("Mahindra & Mahindra", 8.2, V_STRONG), P("Escorts Kubota", 7.6, V_STRONG), P("TAFE (unlisted)", 7.0, V_SOLID), P("VST Tillers Tractors", 6.6, V_SOLID, True), P("International Tractors (Sonalika)", 6.2, V_AVG), P("Action Construction", 6.8, V_SOLID)],
                   "why": "Dominant power-tiller niche with Mitsubishi tech but small-tractor competition and monsoon cyclicality.",
                   "best_own": {"name": "Mahindra & Mahindra", "why": "#1 tractors + scale"}, "avoid": {"name": "International Tractors (Sonalika)", "why": "price-led, thin"}},
    "ECOSMOBLTY": {"set": "Corporate mobility / car rental (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Uber (global)", 7.6, V_STRONG), P("Ola (unlisted)", 7.0, V_SOLID), P("ECOS Mobility", 6.6, V_SOLID, True), P("Carzonrent", 6.0, V_AVG), P("Savaari", 5.8, V_AVG), P("Avis India (unlisted)", 5.8, V_AVG)],
                   "why": "Asset-light B2B employee-transport leader with high ROE but fragmented, price-competitive market.",
                   "best_own": {"name": "ECOS Mobility", "why": "asset-light, profitable B2B"}, "avoid": {"name": "Savaari", "why": "sub-scale"}},
    "LANDMARK": {"set": "Premium auto dealerships (India)", "of": 6, "rank": 1, "action": "HOLD",
                 "peers": [P("Landmark Cars", 6.8, V_SOLID, True), P("TVS Mobility (unlisted)", 6.6, V_SOLID), P("Popular Vehicles", 6.2, V_AVG), P("Sai Service (unlisted)", 6.0, V_AVG), P("Jaybharat Automobiles", 5.8, V_AVG), P("Group Landmark", 5.6, V_AVG)],
                 "why": "Largest premium multi-brand dealer with high-margin after-sales, but OEM agency-model shift and cyclicality.",
                 "best_own": {"name": "Landmark Cars", "why": "premium mix + service annuity"}, "avoid": {"name": "Popular Vehicles", "why": "mass-market thin margins"}},
    "MENONBE": {"set": "Engine bearings & castings (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Schaeffler India", 7.8, V_STRONG), P("SKF India", 7.6, V_STRONG), P("NRB Bearings", 6.8, V_SOLID), P("Menon Bearings", 6.6, V_SOLID, True), P("Rico Auto", 6.0, V_AVG), P("Talbros Engineering", 5.8, V_AVG)],
                "why": "Dominant aluminium engine-bearing niche with 22% ROE and dividends but ICE-EV risk and Maruti concentration.",
                "best_own": {"name": "Schaeffler India", "why": "breadth + EV content"}, "avoid": {"name": "Rico Auto", "why": "low-margin, cyclical"}},
    "ARE&M": {"set": "Batteries & energy storage (India)", "of": 6, "rank": 3, "action": "HOLD",
              "peers": [P("HBL Engineering", 7.6, V_STRONG), P("Exide Industries", 7.4, V_STRONG), P("Amara Raja Energy", 7.2, V_SOLID, True), P("High Energy Batteries", 6.4, V_SOLID), P("Eveready Industries", 6.0, V_AVG), P("Okaya", 5.8, V_AVG)],
              "why": "#2 lead-acid maker with strong cash and a new Li-ion gigafactory push, but lead-acid maturity and cell-execution risk.",
              "best_own": {"name": "Exide Industries", "why": "scale + Li-ion lead"}, "avoid": {"name": "Okaya", "why": "sub-scale"}},
    "RIR": {"set": "Power semiconductors (India)", "of": 6, "rank": 4, "action": "HOLD",
            "peers": [P("ABB India", 8.0, V_STRONG), P("BHEL (power electronics)", 6.2, V_AVG), P("Centum Electronics", 6.0, V_AVG), P("RIR Power Electronics", 5.8, V_AVG, True), P("Salzer Electronics", 6.4, V_SOLID), P("Honeywell Automation", 7.4, V_STRONG)],
            "why": "Niche rectifiers/thyristors for heavy industry but very small, recent earnings decline and very high PE.",
            "best_own": {"name": "ABB India", "why": "scale + technology"}, "avoid": {"name": "BHEL (power electronics)", "why": "weak returns"}},
    "SCODATUBES": {"set": "Precision steel tubes (India)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Tube Investments", 8.0, V_STRONG), P("APL Apollo Tubes", 7.8, V_STRONG), P("Goodluck India", 6.8, V_SOLID), P("Hariom Pipe", 6.6, V_SOLID), P("Scoda Tubes", 6.0, V_AVG, True), P("Rama Steel Tubes", 5.8, V_AVG)],
                   "why": "Precision cold-drawn tube import-substitution niche but tiny scale and steel-price margin swings.",
                   "best_own": {"name": "Tube Investments", "why": "diversified, high-RoCE"}, "avoid": {"name": "Rama Steel Tubes", "why": "sub-scale, volatile"}},
    "MODISONLTD": {"set": "Electrical contacts & bimetals (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Honeywell (global)", 7.6, V_STRONG), P("Shivalik Bimetal Controls", 7.0, V_SOLID), P("Modison", 6.8, V_SOLID, True), P("Salzer Electronics", 6.6, V_SOLID), P("Igarashi Motors", 6.0, V_AVG), P("Precision Wires", 6.2, V_AVG)],
                   "why": "~60% share in silver electrical contacts with recycling edge and high growth but silver-price working-capital swings.",
                   "best_own": {"name": "Shivalik Bimetal Controls", "why": "IP + consistent returns"}, "avoid": {"name": "Igarashi Motors", "why": "concentrated, cyclical"}},
    "SALZERELEC": {"set": "Electrical components / switchgear (India)", "of": 6, "rank": 4, "action": "HOLD",
                   "peers": [P("Schneider Electric", 7.6, V_STRONG), P("Shilchar Technologies", 7.0, V_SOLID), P("Modison", 6.8, V_SOLID), P("Salzer Electronics", 6.6, V_SOLID, True), P("HPL Electric", 6.0, V_AVG), P("RR Kabel (adjacent)", 6.4, V_SOLID)],
                   "why": "ATEX-certified cam-switch niche and exports but small scale, low ROE and high working capital.",
                   "best_own": {"name": "Schneider Electric", "why": "scale + brand"}, "avoid": {"name": "HPL Electric", "why": "leveraged, low returns"}},
    "BBL": {"set": "Transformers & motors (India)", "of": 6, "rank": 5, "action": "HOLD",
            "peers": [P("Hitachi Energy India", 8.5, V_LEADER), P("ABB India", 8.0, V_STRONG), P("Voltamp Transformers", 7.2, V_SOLID), P("Transformers & Rectifiers", 6.8, V_SOLID), P("Bharat Bijlee", 6.6, V_SOLID, True), P("Indo Tech Transformers", 6.0, V_AVG)],
            "why": "70-year transformer+HT-motor maker riding grid capex but negative OCF and lower returns than focused peers.",
            "best_own": {"name": "Voltamp Transformers", "why": "debt-free, high-RoCE pure-play"}, "avoid": {"name": "Indo Tech Transformers", "why": "sub-scale"}},
    "LAKSELEC": {"set": "Industrial control panels (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("ABB India", 8.0, V_STRONG), P("Schneider Electric", 7.6, V_STRONG), P("Salzer Electronics", 6.6, V_SOLID), P("HPL Electric", 6.0, V_AVG), P("Lakshmi Electrical Control", 5.4, V_WEAK, True), P("C&S Electric (unlisted)", 5.2, V_WEAK)],
                 "why": "Niche MCC/panel maker but very small, recent losses and illiquid.",
                 "best_own": {"name": "ABB India", "why": "scale + technology"}, "avoid": {"name": "Lakshmi Electrical Control", "why": "loss-making, illiquid"}},
    "UNIVCABLES": {"set": "EHV / power cables (India)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Polycab India", 8.2, V_STRONG), P("KEI Industries", 8.0, V_STRONG), P("RR Kabel", 7.0, V_SOLID), P("Sterlite Power (unlisted)", 6.8, V_SOLID), P("Universal Cables", 6.4, V_SOLID, True), P("Ultracab India", 5.8, V_AVG)],
                   "why": "One of few EHV cable makers with Birla backing but small scale and lower returns vs Polycab/KEI.",
                   "best_own": {"name": "Polycab India", "why": "scale + brand + B2C mix"}, "avoid": {"name": "Ultracab India", "why": "sub-scale"}},
    "GMDCLTD": {"set": "Mining / minerals (India)", "of": 6, "rank": 5, "action": "HOLD",
                "peers": [P("NMDC", 8.0, V_STRONG), P("Coal India", 7.8, V_STRONG), P("Vedanta", 6.8, V_SOLID), P("MOIL", 6.6, V_SOLID), P("GMDC", 6.4, V_SOLID, True), P("Sandur Manganese", 6.2, V_AVG)],
                "why": "Exclusive Gujarat lignite/bauxite leases with lithium optionality but mineral cyclicality and declining lignite.",
                "best_own": {"name": "NMDC", "why": "lowest-cost iron ore + scale"}, "avoid": {"name": "Sandur Manganese", "why": "small, commodity-cyclical"}},
    "EIMCOELECO": {"set": "Mining equipment (India)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Sandvik (global)", 8.0, V_STRONG), P("Epiroc (global)", 8.0, V_STRONG), P("Tega Industries", 7.4, V_STRONG), P("Elecon Engineering", 7.0, V_SOLID), P("Eimco Elecon", 6.2, V_AVG, True), P("Revathi Equipment", 5.8, V_AVG)],
                   "why": "Near-monopoly underground LHD for Coal India but monopsony customer and structurally declining underground mining.",
                   "best_own": {"name": "Sandvik (global)", "why": "global tech + scale"}, "avoid": {"name": "Revathi Equipment", "why": "sub-scale"}},
    "TEGA": {"set": "Mineral-processing wear parts (global)", "of": 6, "rank": 4, "action": "HOLD",
             "peers": [P("Metso (global)", 8.2, V_STRONG), P("Weir Group (global)", 8.0, V_STRONG), P("AIA Engineering", 7.6, V_STRONG), P("Tega Industries", 7.2, V_SOLID, True), P("Trelleborg", 7.0, V_SOLID), P("ME Elecmetal", 6.8, V_SOLID)],
             "why": "Global #2 in polymer mill-liners with IP and high switching cost but mining-capex cyclicality and a recent PAT dip.",
             "best_own": {"name": "AIA Engineering", "why": "high-RoCE grinding-media leader"}, "avoid": {"name": "ME Elecmetal", "why": "narrower franchise"}},
    "GRAPHITE": {"set": "Graphite electrodes (global)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Tokai Carbon", 7.6, V_STRONG), P("Showa Denko", 7.4, V_STRONG), P("HEG", 7.2, V_SOLID), P("GrafTech", 7.0, V_SOLID), P("Graphite India", 6.8, V_SOLID, True), P("SGL Carbon", 6.4, V_SOLID)],
                 "why": "One of two Indian UHP-electrode makers with EU ops but electrode-price cyclicality and low ROE.",
                 "best_own": {"name": "HEG", "why": "captive needle coke + scale"}, "avoid": {"name": "SGL Carbon", "why": "weaker electrode franchise"}},
    "HEG": {"set": "Graphite electrodes (global)", "of": 6, "rank": 3, "action": "HOLD",
            "peers": [P("Tokai Carbon", 7.6, V_STRONG), P("Showa Denko", 7.4, V_STRONG), P("HEG", 7.2, V_SOLID, True), P("GrafTech", 7.0, V_SOLID), P("Graphite India", 6.8, V_SOLID), P("SGL Carbon", 6.4, V_SOLID)],
            "why": "India's largest electrode exporter with captive needle-coke and a GrafTech stake; cyclical but best-positioned domestically.",
            "best_own": {"name": "HEG", "why": "captive coke + anode optionality"}, "avoid": {"name": "SGL Carbon", "why": "weaker franchise"}},
    "USHAMART": {"set": "Specialty wire rope (global)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Bekaert (global)", 7.6, V_STRONG), P("Usha Martin", 7.4, V_STRONG, True), P("Kiswire (global)", 7.0, V_SOLID), P("WireCo", 6.8, V_SOLID), P("Gustav Wolf", 6.4, V_SOLID), P("Bharat Wire Ropes", 6.0, V_AVG)],
                 "why": "Global specialty wire-rope leader post-steel exit with qualification moat and rising ROCE; behind only Bekaert on scale.",
                 "best_own": {"name": "Usha Martin", "why": "focused specialty leader"}, "avoid": {"name": "Bharat Wire Ropes", "why": "sub-scale, leveraged"}},
    "KAMDHENU": {"set": "Branded TMT & building materials (India)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Tata Steel (branded)", 8.0, V_STRONG), P("JSW Steel", 7.8, V_STRONG), P("Shyam Metalics", 7.0, V_SOLID), P("Kamdhenu", 6.6, V_SOLID, True), P("Sunflag Iron", 6.0, V_AVG), P("Rama Steel", 5.8, V_AVG)],
                 "why": "Asset-light franchise brand plus paints cross-sell with 22% ROE but commodity-linked TMT and small base.",
                 "best_own": {"name": "Tata Steel (branded)", "why": "integrated scale + brand"}, "avoid": {"name": "Rama Steel", "why": "sub-scale"}},
    "MMP": {"set": "Aluminium powder & paste (global niche)", "of": 6, "rank": 4, "action": "HOLD",
            "peers": [P("Eckart (global)", 7.6, V_STRONG), P("Silberline", 7.2, V_SOLID), P("Toyal", 6.8, V_SOLID), P("MMP Industries", 6.6, V_SOLID, True), P("Sun Chemical", 6.4, V_SOLID), P("Metal Powder Co", 6.0, V_AVG)],
            "why": "Dominant Indian aluminium-powder/paste maker with exports but LME-linked margins and small scale.",
            "best_own": {"name": "Eckart (global)", "why": "tech + global scale"}, "avoid": {"name": "Metal Powder Co", "why": "sub-scale"}},
    "IFGLEXPOR": {"set": "Refractories (India)", "of": 6, "rank": 4, "action": "HOLD",
                  "peers": [P("RHI Magnesita India", 8.0, V_STRONG), P("Vesuvius India", 7.4, V_STRONG), P("TRL Krosaki", 6.8, V_SOLID), P("IFGL Refractories", 6.6, V_SOLID, True), P("Calderys (unlisted)", 6.4, V_SOLID), P("Manishri Refractories", 5.8, V_AVG)],
                  "why": "Specialised steel-refractory maker with exports but steel-capex cyclicality and mid-pack returns.",
                  "best_own": {"name": "RHI Magnesita India", "why": "scale + global tech"}, "avoid": {"name": "Manishri Refractories", "why": "sub-scale"}},
    "BOROSCI": {"set": "Scientific glassware (India + global)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Schott (global)", 7.8, V_STRONG), P("Eppendorf (global)", 7.6, V_STRONG), P("DWK Life Sciences", 7.4, V_STRONG), P("Borosil Scientific", 6.8, V_SOLID, True), P("Tarsons Products", 6.6, V_SOLID), P("Praxis", 5.8, V_AVG)],
                "why": "Dominant Indian lab-glassware brand with 50-year trust but small scale and input-cost margins.",
                "best_own": {"name": "Schott (global)", "why": "tech + global breadth"}, "avoid": {"name": "Tarsons Products", "why": "post-IPO derating"}},
    "SIGNPOST": {"set": "Out-of-home advertising (India)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Times OOH (unlisted)", 7.0, V_SOLID), P("Signpost India", 6.8, V_SOLID, True), P("Laqshya Media (unlisted)", 6.6, V_SOLID), P("Bright Outdoor", 6.0, V_AVG), P("Selvel One", 5.8, V_AVG), P("Pioneer Publicity", 5.6, V_AVG)],
                 "why": "Municipal-concession street-furniture moat with digital-OOH growth and 27% ROE but small and contract-renewal risk.",
                 "best_own": {"name": "Signpost India", "why": "concession moat + returns"}, "avoid": {"name": "Selvel One", "why": "sub-scale"}},
    "RKSWAMY": {"set": "Advertising & market research (India)", "of": 6, "rank": 5, "action": "HOLD",
                "peers": [P("WPP / GroupM (global)", 8.0, V_STRONG), P("Affle India (adjacent)", 7.6, V_STRONG), P("Dentsu", 7.4, V_STRONG), P("Latent View (adjacent)", 6.6, V_SOLID), P("R K Swamy", 6.4, V_SOLID, True), P("Madison World (unlisted)", 6.0, V_AVG)],
                "why": "Integrated agency with PSU/BFSI relationships and Bharat reach but digital disruption and holding-co model.",
                "best_own": {"name": "WPP / GroupM (global)", "why": "scale + global clients"}, "avoid": {"name": "Nazara (adjacent)", "why": "different, volatile model"}},
    "QUESS": {"set": "Staffing & business services (India)", "of": 6, "rank": 3, "action": "HOLD",
              "peers": [P("TeamLease Services", 7.4, V_STRONG), P("ManpowerGroup (global)", 7.2, V_SOLID), P("Quess Corp", 7.0, V_SOLID, True), P("Adecco (global)", 7.0, V_SOLID), P("SIS Limited", 6.8, V_SOLID), P("Updater Services", 6.2, V_AVG)],
              "why": "India's largest staffing platform with Allsec tech and 20% ROE but low-margin, working-capital-heavy model.",
              "best_own": {"name": "TeamLease Services", "why": "focused, asset-light"}, "avoid": {"name": "Updater Services", "why": "thin facility-management margins"}},
    "CMSINFO": {"set": "Cash management / ATM services (India)", "of": 6, "rank": 1, "action": "HOLD",
                "peers": [P("CMS Info Systems", 7.4, V_STRONG, True), P("Loomis (global)", 7.2, V_SOLID), P("Brinks (global)", 7.0, V_SOLID), P("SIS Cash Services", 6.4, V_SOLID), P("Radiant Cash", 6.0, V_AVG), P("AGS Transact", 5.0, V_WEAK)],
                "why": "India's largest cash-management network with an RBI-regulated moat and strong cash, though UPI is a long-term threat.",
                "best_own": {"name": "CMS Info Systems", "why": "scale + recurring contracts"}, "avoid": {"name": "AGS Transact", "why": "financial stress"}},
    "DIFFNKG": {"set": "Wear-parts & welding consumables (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Esab India", 7.4, V_STRONG), P("Ador Welding", 7.2, V_SOLID), P("EWAC Alloys (unlisted)", 6.8, V_SOLID), P("Diffusion Engineers", 6.6, V_SOLID, True), P("D&H Secheron", 6.4, V_SOLID), P("GEE Limited", 6.0, V_AVG)],
                "why": "Niche asset-life-enhancement and wear-parts maker with 40% earnings growth but small and capex-cyclical.",
                "best_own": {"name": "Esab India", "why": "leader + high RoCE"}, "avoid": {"name": "GEE Limited", "why": "sub-scale"}},
    "SHREEJISPG": {"set": "Shipping & marine logistics (India)", "of": 6, "rank": 5, "action": "HOLD",
                   "peers": [P("Great Eastern Shipping", 8.0, V_STRONG), P("Gujarat Pipavav Port", 7.0, V_SOLID), P("Seamec", 6.8, V_SOLID), P("Shipping Corp of India", 6.4, V_SOLID), P("Shreeji Shipping Global", 6.2, V_AVG, True), P("Mercator", 4.5, V_WEAK)],
                   "why": "Dry-bulk transshipment and logistics niche but freight cyclicality, small fleet and newly listed.",
                   "best_own": {"name": "Great Eastern Shipping", "why": "diversified fleet + balance sheet"}, "avoid": {"name": "Mercator", "why": "defunct cautionary"}},
    "GESHIP": {"set": "Shipping (India)", "of": 6, "rank": 1, "action": "HOLD",
               "peers": [P("Great Eastern Shipping", 8.0, V_STRONG, True), P("Frontline (global)", 7.4, V_STRONG), P("Seamec", 6.8, V_SOLID), P("Shipping Corp of India", 6.4, V_SOLID), P("Shreeji Shipping Global", 6.2, V_AVG), P("Mercator", 4.5, V_WEAK)],
               "why": "India's largest private shipper with a diversified fleet, strong balance sheet and through-cycle dividends — best capital allocation in the set.",
               "best_own": {"name": "Great Eastern Shipping", "why": "balance sheet + dividends"}, "avoid": {"name": "Mercator", "why": "defunct cautionary"}},
    "SCI": {"set": "Shipping (India)", "of": 6, "rank": 4, "action": "HOLD",
            "peers": [P("Great Eastern Shipping", 8.0, V_STRONG), P("Frontline (global)", 7.4, V_STRONG), P("Seamec", 6.8, V_SOLID), P("Shipping Corp of India", 6.4, V_SOLID, True), P("Shreeji Shipping Global", 6.2, V_AVG), P("Mercator", 4.5, V_WEAK)],
            "why": "India's only PSU shipper with government cargo access but PSU inefficiency and a privatisation overhang.",
            "best_own": {"name": "Great Eastern Shipping", "why": "best private operator"}, "avoid": {"name": "Mercator", "why": "defunct cautionary"}},
    "NIFTYBEES": {"set": "Large-cap index ETFs (India)", "of": 6, "rank": 1, "action": "HOLD",
                  "peers": [P("Nippon Nifty BeES", 7.4, V_STRONG, True), P("SBI Nifty 50 ETF", 7.2, V_SOLID), P("UTI Nifty 50 ETF", 7.2, V_SOLID), P("ICICI Nifty 50 ETF", 7.0, V_SOLID), P("HDFC Nifty 50 ETF", 7.0, V_SOLID), P("Kotak Nifty 50 ETF", 6.8, V_SOLID)],
                  "why": "Oldest, most-liquid Nifty-50 ETF with tightest tracking and deepest on-exchange liquidity.",
                  "best_own": {"name": "Nippon Nifty BeES", "why": "liquidity + low tracking error"}, "avoid": {"name": "Kotak Nifty 50 ETF", "why": "thinner liquidity"}},
    "MON100": {"set": "US-tech index ETFs (India)", "of": 6, "rank": 1, "action": "HOLD",
               "peers": [P("Motilal Oswal Nasdaq 100", 7.2, V_SOLID, True), P("ICICI Nasdaq 100 ETF", 7.0, V_SOLID), P("Kotak Nasdaq 100 FoF", 6.8, V_SOLID), P("Mirae S&P 500 ETF", 7.0, V_SOLID), P("Mirae NYSE FANG+", 6.6, V_SOLID), P("Navi Nasdaq 100 FoF", 6.6, V_SOLID)],
               "why": "Largest, longest-track Nasdaq-100 onshore wrapper with reasonable tracking; subject to subscription caps.",
               "best_own": {"name": "Motilal Oswal Nasdaq 100", "why": "scale + track record"}, "avoid": {"name": "Navi Nasdaq 100 FoF", "why": "newer, smaller"}},
    "MAFANG": {"set": "US-tech thematic ETFs (India)", "of": 6, "rank": 5, "action": "HOLD",
               "peers": [P("Motilal Oswal Nasdaq 100", 7.2, V_SOLID), P("Mirae S&P 500 ETF", 7.0, V_SOLID), P("ICICI Nasdaq 100 ETF", 7.0, V_SOLID), P("Kotak Nasdaq 100 FoF", 6.8, V_SOLID), P("Mirae NYSE FANG+", 6.6, V_SOLID, True), P("Navi US Tech FoF", 6.2, V_AVG)],
               "why": "Concentrated equal-weight FANG+ basket — higher beta and volatility than diversified Nasdaq-100/S&P wrappers.",
               "best_own": {"name": "Motilal Oswal Nasdaq 100", "why": "diversified, lower concentration"}, "avoid": {"name": "Navi US Tech FoF", "why": "newer, smaller"}},
    "AEROFLEX": {"set": "SS flexible hoses / engineered products (India)", "of": 6, "rank": 1, "action": "HOLD",
                 "peers": [P("Aeroflex Industries", 7.6, V_STRONG, True), P("Mitsubishi (hose, global)", 7.4, V_STRONG), P("Witzenmann (global)", 7.2, V_SOLID), P("Technocraft Industries", 7.0, V_SOLID), P("Hi-Tech Pipes", 6.4, V_SOLID), P("Sat Industries (parent)", 6.0, V_AVG)],
                 "why": "Only scaled Indian SS-flexible-hose maker (~75% share) with a BIS-QCO barrier and 56% PAT CAGR; leads domestically.",
                 "best_own": {"name": "Aeroflex Industries", "why": "domestic monopoly + exports"}, "avoid": {"name": "Sat Industries (parent)", "why": "holding-co complexity"}},
    "KENNAMET": {"set": "Cutting tools (India + global)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Sandvik (global)", 8.2, V_STRONG), P("Iscar (global)", 7.8, V_STRONG), P("Mitsubishi Materials", 7.2, V_SOLID), P("Kennametal India", 7.0, V_SOLID, True), P("Addison & Co", 6.2, V_AVG), P("Birla Precision", 6.0, V_AVG)],
                 "why": "Premium tungsten-carbide tooling with US-parent IP but cyclical capex demand and a full valuation.",
                 "best_own": {"name": "Sandvik (global)", "why": "scale + R&D leadership"}, "avoid": {"name": "Birla Precision", "why": "sub-scale"}},
    "HONAUT": {"set": "Process automation (India)", "of": 6, "rank": 4, "action": "HOLD",
               "peers": [P("ABB India", 8.2, V_STRONG), P("Emerson (global)", 7.8, V_STRONG), P("Siemens", 7.6, V_STRONG), P("Honeywell Automation", 7.4, V_STRONG, True), P("Yokogawa India", 7.2, V_SOLID), P("Rockwell Automation", 7.0, V_SOLID)],
               "why": "#1 in DCS process automation with extreme switching cost and parent IP, but illiquid stock and slow revenue growth.",
               "best_own": {"name": "ABB India", "why": "broader mix + high RoCE"}, "avoid": {"name": "Rockwell Automation", "why": "smaller India presence"}},
    "SKFINDUS": {"set": "Bearings (India)", "of": 6, "rank": 2, "action": "HOLD",
                 "peers": [P("Schaeffler India", 7.8, V_STRONG), P("SKF India", 7.4, V_STRONG, True), P("Timken India", 7.2, V_SOLID), P("AB SKF (global)", 7.0, V_SOLID), P("NRB Bearings", 6.4, V_SOLID), P("NEI / Tata Bearings", 6.0, V_AVG)],
                 "why": "Top-2 bearing maker with strong after-market and ~29% ROE; Schaeffler leads on breadth and EV content.",
                 "best_own": {"name": "Schaeffler India", "why": "broadest portfolio + EV"}, "avoid": {"name": "NEI / Tata Bearings", "why": "sub-scale"}},
    "INGERRAND": {"set": "Air compressors (India)", "of": 6, "rank": 3, "action": "HOLD",
                  "peers": [P("Atlas Copco", 8.4, V_LEADER), P("Elgi Equipment", 7.5, V_STRONG), P("Ingersoll Rand India", 7.4, V_STRONG, True), P("Gardner Denver", 7.0, V_SOLID), P("Kirloskar Pneumatic", 6.8, V_SOLID), P("Sullair / Hitachi", 6.4, V_SOLID)],
                  "why": "US-parent brand with 42% ROE and high margins but cyclical capex and a recent revenue dip.",
                  "best_own": {"name": "Atlas Copco", "why": "global scale + margins"}, "avoid": {"name": "Sullair / Hitachi", "why": "weaker India franchise"}},
    "KIRLPNU": {"set": "Compressors & process equipment (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Atlas Copco", 8.4, V_LEADER), P("Elgi Equipment", 7.5, V_STRONG), P("Ingersoll Rand India", 7.4, V_STRONG), P("Kirloskar Pneumatic", 7.0, V_SOLID, True), P("Kirloskar Brothers", 6.6, V_SOLID), P("Sullair / Hitachi", 6.4, V_SOLID)],
                "why": "Defence-refrigeration plus industrial compressors with 21% ROE and a strong order book but niche scale.",
                "best_own": {"name": "Atlas Copco", "why": "scale + margins"}, "avoid": {"name": "Sullair / Hitachi", "why": "weaker franchise"}},
    "ISGEC": {"set": "Heavy engineering / EPC (India)", "of": 6, "rank": 5, "action": "HOLD",
              "peers": [P("Larsen & Toubro", 8.0, V_STRONG), P("Triveni Turbine", 7.6, V_STRONG), P("Thermax", 7.5, V_STRONG), P("Praj Industries", 7.2, V_SOLID), P("Isgec Heavy Engineering", 6.6, V_SOLID, True), P("BHEL", 5.5, V_WEAK)],
              "why": "Multi-product boilers/presses/sugar-equipment with global reach but lumpy projects and low ROE.",
              "best_own": {"name": "Larsen & Toubro", "why": "execution + diversification"}, "avoid": {"name": "BHEL", "why": "weak returns, PSU drag"}},
    "JNKINDIA": {"set": "Process-fired heaters / EPC (India)", "of": 6, "rank": 3, "action": "HOLD",
                 "peers": [P("Thermax", 7.5, V_STRONG), P("Praj Industries", 7.2, V_SOLID), P("JNK India", 7.0, V_SOLID, True), P("Isgec Heavy Engineering", 6.6, V_SOLID), P("Tema India", 6.0, V_AVG), P("BHEL", 5.5, V_WEAK)],
                 "why": "Exclusive Korean fired-heater technology with green-H2 optionality and 146% PAT CAGR but project-lumpy and small.",
                 "best_own": {"name": "Thermax", "why": "integrated, diversified"}, "avoid": {"name": "BHEL", "why": "weak returns"}},
    "POWERICA": {"set": "Diesel gensets & power equipment (India)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Cummins India", 8.0, V_STRONG), P("Kirloskar Oil Engines", 7.4, V_STRONG), P("Mahindra Powerol", 7.0, V_SOLID), P("Powerica", 6.6, V_SOLID, True), P("Jakson (unlisted)", 6.4, V_SOLID), P("Greaves Cotton", 6.2, V_AVG)],
                 "why": "Largest independent Cummins DG dealer with AMC recurring revenue and data-centre demand but grid-reliability long-term risk.",
                 "best_own": {"name": "Cummins India", "why": "OEM moat + cash"}, "avoid": {"name": "Greaves Cotton", "why": "EV-transition drag"}},
    "ENRIN": {"set": "Power generation & grid equipment (India)", "of": 6, "rank": 3, "action": "HOLD",
              "peers": [P("Hitachi Energy India", 8.7, V_LEADER), P("ABB India", 8.3, V_STRONG), P("Siemens Energy India", 7.6, V_STRONG, True), P("GE Vernova T&D India", 7.4, V_STRONG), P("CG Power", 7.2, V_SOLID), P("BHEL", 5.5, V_WEAK)],
              "why": "Gas-turbine + grid + transmission franchise with parent technology riding energy capex; behind Hitachi/ABB on returns.",
              "best_own": {"name": "Hitachi Energy India", "why": "HVDC franchise + RoCE"}, "avoid": {"name": "BHEL", "why": "weak returns"}},
    "CESC": {"set": "Integrated power utilities (India)", "of": 6, "rank": 5, "action": "HOLD",
             "peers": [P("NTPC", 8.0, V_STRONG), P("Tata Power", 7.6, V_STRONG), P("Torrent Power", 7.4, V_STRONG), P("JSW Energy", 7.2, V_SOLID), P("CESC", 6.8, V_SOLID, True), P("Adani Power", 6.6, V_SOLID)],
             "why": "100-year Kolkata distribution monopoly with DISCOM-privatisation optionality but regulated returns and high debt.",
             "best_own": {"name": "Tata Power", "why": "RE growth + distribution mix"}, "avoid": {"name": "Adani Power", "why": "leverage + governance optics"}},
    "GIPCL": {"set": "PSU / state power gencos (India)", "of": 6, "rank": 4, "action": "HOLD",
              "peers": [P("NTPC", 8.0, V_STRONG), P("NHPC", 7.2, V_SOLID), P("SJVN", 6.6, V_SOLID), P("GIPCL", 6.6, V_SOLID, True), P("NLC India", 6.4, V_SOLID), P("Jaiprakash Power", 5.5, V_WEAK)],
              "why": "Long-term GUVNL PPAs plus lignite cost edge and cheap valuation but lignite sunset and limited growth.",
              "best_own": {"name": "NTPC", "why": "scale + RE pivot"}, "avoid": {"name": "Jaiprakash Power", "why": "leveraged, weak"}},
    "NLCINDIA": {"set": "PSU power gencos (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("NTPC", 8.0, V_STRONG), P("NHPC", 7.2, V_SOLID), P("SJVN", 6.6, V_SOLID), P("GIPCL", 6.6, V_SOLID), P("NLC India", 6.4, V_SOLID, True), P("Jaiprakash Power", 5.5, V_WEAK)],
                 "why": "Lignite miner-genco with captive cost edge and an RE pivot but polluting-fuel transition and PSU pace.",
                 "best_own": {"name": "NTPC", "why": "scale + RE pivot"}, "avoid": {"name": "Jaiprakash Power", "why": "leveraged, weak"}},
    "SJVN": {"set": "Hydro / RE PSU gencos (India)", "of": 6, "rank": 3, "action": "HOLD",
             "peers": [P("NTPC", 8.0, V_STRONG), P("NHPC", 7.4, V_STRONG), P("SJVN", 6.6, V_SOLID, True), P("GIPCL", 6.6, V_SOLID), P("NLC India", 6.4, V_SOLID), P("Jaiprakash Power", 5.5, V_WEAK)],
             "why": "Hydro concessions plus an aggressive 25GW RE target but long gestation and low current ROE.",
             "best_own": {"name": "NTPC", "why": "scale + execution"}, "avoid": {"name": "Jaiprakash Power", "why": "leveraged, weak"}},
    "PFC": {"set": "Power-sector NBFCs (India)", "of": 6, "rank": 2, "action": "HOLD",
            "peers": [P("REC", 7.4, V_STRONG), P("Power Finance Corp", 7.2, V_SOLID, True), P("IREDA", 7.0, V_SOLID), P("IRFC", 6.8, V_SOLID), P("L&T Finance", 6.4, V_SOLID), P("PTC India Financial Services", 6.0, V_AVG)],
            "why": "Largest power-sector financier with sovereign-backed funding and 20% ROE but DISCOM credit risk.",
            "best_own": {"name": "REC", "why": "similar moat, cleaner book"}, "avoid": {"name": "L&T Finance", "why": "more competitive lending"}},
    "PTC": {"set": "Power trading & exchanges (India)", "of": 6, "rank": 3, "action": "HOLD",
            "peers": [P("Indian Energy Exchange", 8.0, V_STRONG), P("Tata Power Trading (unlisted)", 6.8, V_SOLID), P("PTC India", 6.6, V_SOLID, True), P("NTPC Vidyut Vyapar", 6.4, V_SOLID), P("PXIL", 6.2, V_AVG), P("Manikaran (unlisted)", 6.0, V_AVG)],
            "why": "Largest bilateral power trader plus cross-border flows with a high dividend but thin trading margins and IEX disintermediation.",
            "best_own": {"name": "Indian Energy Exchange", "why": "exchange network-effect moat"}, "avoid": {"name": "Manikaran (unlisted)", "why": "sub-scale"}},
    "KPIGREEN": {"set": "Solar IPP / EPC (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Adani Green", 7.6, V_STRONG), P("Tata Power Renewables", 7.4, V_STRONG), P("Waaree Energies", 7.2, V_SOLID), P("Premier Energies", 7.0, V_SOLID), P("KPI Green Energy", 6.8, V_SOLID, True), P("Sterling & Wilson", 6.4, V_SOLID)],
                 "why": "Fast-growing solar IPP+EPC with 47% PAT CAGR and a captive-CPP model but high leverage and execution intensity.",
                 "best_own": {"name": "Tata Power Renewables", "why": "balance sheet + integration"}, "avoid": {"name": "Sterling & Wilson", "why": "lumpy EPC, past stress"}},
    "CLEANMAX": {"set": "C&I rooftop / open-access solar (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Adani Green", 7.6, V_STRONG), P("Tata Power Renewables", 7.4, V_STRONG), P("Amplus Solar (unlisted)", 6.8, V_SOLID), P("KPI Green Energy", 6.8, V_SOLID), P("CleanMax Enviro", 6.6, V_SOLID, True), P("Fourth Partner (unlisted)", 6.6, V_SOLID)],
                 "why": "Leading C&I solar developer with marquee corporate clients but very high leverage and low ROE.",
                 "best_own": {"name": "Tata Power Renewables", "why": "scale + balance sheet"}, "avoid": {"name": "Fourth Partner (unlisted)", "why": "high-debt growth"}},
    "DEEDEV": {"set": "Industrial piping / process equipment (India)", "of": 6, "rank": 5, "action": "HOLD",
               "peers": [P("Thermax", 7.5, V_STRONG), P("Praj Industries", 7.2, V_SOLID), P("Welspun Corp", 7.0, V_SOLID), P("Isgec Heavy Engineering", 6.6, V_SOLID), P("Dee Development Engineers", 6.4, V_SOLID, True), P("Man Industries", 6.0, V_AVG)],
               "why": "IBR/ASME-certified high-pressure piping for refineries/power with a moat but project-lumpy revenue, low ROE and high D/E.",
               "best_own": {"name": "Thermax", "why": "diversified, high RoCE"}, "avoid": {"name": "Man Industries", "why": "commodity pipe cycle"}},
    "SOUTHWEST": {"set": "Oilfield / drilling services (India)", "of": 6, "rank": 3, "action": "HOLD",
                  "peers": [P("Deep Industries", 6.8, V_SOLID), P("Jindal Drilling", 6.4, V_SOLID), P("South West Pinnacle", 6.2, V_AVG, True), P("Asian Energy Services", 6.0, V_AVG), P("Dolphin Offshore", 5.8, V_AVG), P("Aban Offshore", 5.5, V_WEAK)],
                  "why": "Niche well-completion/exploration services with ONGC ties and decent ROE but monopsony customer and oil-price sensitivity.",
                  "best_own": {"name": "Deep Industries", "why": "diversified gas-services + returns"}, "avoid": {"name": "Aban Offshore", "why": "debt distress"}},
    "GALAPREC": {"set": "Precision springs & fasteners (India)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Sundram Fasteners", 7.6, V_STRONG), P("Sansera Engineering", 7.2, V_SOLID), P("Ramkrishna Forgings", 6.8, V_SOLID), P("Gala Precision Engineering", 6.6, V_SOLID, True), P("Talbros Engineering", 6.0, V_AVG), P("Mahindra CIE", 6.4, V_SOLID)],
                 "why": "Precision coil/disc-spring exporter with certifications and 20%+ growth but small scale and customer concentration.",
                 "best_own": {"name": "Sundram Fasteners", "why": "scale + RoCE"}, "avoid": {"name": "Talbros Engineering", "why": "thin, cyclical"}},
    "HAPPYFORGE": {"set": "Forgings (India)", "of": 6, "rank": 3, "action": "HOLD",
                   "peers": [P("Bharat Forge", 7.8, V_STRONG), P("Sundram Fasteners", 7.6, V_STRONG), P("Happy Forgings", 7.2, V_SOLID, True), P("CIE Automotive India", 7.0, V_SOLID), P("Ramkrishna Forgings", 6.8, V_SOLID), P("MM Forgings", 6.2, V_AVG)],
                   "why": "Largest 14,000-tonne press line with multi-sector diversification and 23% PAT CAGR; behind Bharat Forge/Sundram on scale.",
                   "best_own": {"name": "Bharat Forge", "why": "scale + defence/export"}, "avoid": {"name": "MM Forgings", "why": "cyclical, lower returns"}},
    "PITTIENG": {"set": "Electrical laminations & components (India)", "of": 6, "rank": 3, "action": "HOLD",
                 "peers": [P("Bharat Forge (adjacent)", 7.6, V_STRONG), P("Shanthi Gears", 7.0, V_SOLID), P("Pitti Engineering", 6.8, V_SOLID, True), P("Bharat Bijlee", 6.6, V_SOLID), P("Indo Tech Transformers", 6.0, V_AVG), P("TD Power Systems", 7.2, V_SOLID)],
                 "why": "GE/Siemens-qualified lamination maker for traction motors with a rail tailwind but CRGO-steel margins and a recent PAT dip.",
                 "best_own": {"name": "TD Power Systems", "why": "generator niche + returns"}, "avoid": {"name": "Indo Tech Transformers", "why": "sub-scale"}},
    "TEJASNET": {"set": "Telecom equipment (India + global)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Ericsson (global)", 7.6, V_STRONG), P("Nokia (global)", 7.4, V_STRONG), P("HFCL", 6.6, V_SOLID), P("Tejas Networks", 6.4, V_SOLID, True), P("Sterlite Technologies", 5.8, V_AVG), P("ITI Limited", 4.5, V_WEAK)],
                 "why": "Only Indian end-to-end telecom-gear IP with BSNL 4G and Tata backing but severe revenue lumpiness and current losses.",
                 "best_own": {"name": "Ericsson (global)", "why": "scale + proven 5G"}, "avoid": {"name": "ITI Limited", "why": "loss-making PSU"}},
    "WELCORP": {"set": "Large-diameter steel pipes (global)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Tenaris (global)", 7.8, V_STRONG), P("Jindal SAW", 7.4, V_STRONG), P("Welspun Corp", 7.2, V_SOLID, True), P("Maharashtra Seamless", 7.0, V_SOLID), P("Ratnamani Metals", 7.2, V_SOLID), P("Man Industries", 6.4, V_SOLID)],
                "why": "Only Indian SAW+ERW maker with a US plant and Sintex diversification but steel/oil-cycle margins and a recent PAT drop.",
                "best_own": {"name": "Ratnamani Metals", "why": "specialty mix + high RoCE"}, "avoid": {"name": "Man Industries", "why": "thin, cyclical"}},
    "SUZLON": {"set": "Wind turbine OEMs (India + global)", "of": 6, "rank": 4, "action": "HOLD",
               "peers": [P("Vestas (global)", 7.6, V_STRONG), P("Inox Wind", 7.0, V_SOLID), P("Siemens Gamesa", 7.0, V_SOLID), P("Suzlon Energy", 6.8, V_SOLID, True), P("GE Wind", 6.8, V_SOLID), P("Senvion (defunct)", 4.5, V_WEAK)],
               "why": "Turnaround with 40% ROE, a clean balance sheet and a large order book but execution-cyclical and past governance scars.",
               "best_own": {"name": "Vestas (global)", "why": "scale + technology"}, "avoid": {"name": "Senvion (defunct)", "why": "bankruptcy cautionary"}},
    "HLEGLAS": {"set": "Glass-lined / process equipment (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Thermax", 7.5, V_STRONG), P("GMM Pfaudler", 7.4, V_STRONG), P("Praj Industries", 7.2, V_SOLID), P("HLE Glascoat", 6.4, V_SOLID, True), P("Standard Glass Lining", 6.2, V_AVG), P("Tema India", 6.0, V_AVG)],
                "why": "#2 glass-lined-equipment maker for pharma/chem capex but recent earnings decline, high D/E and cyclicality.",
                "best_own": {"name": "GMM Pfaudler", "why": "global glass-lining leader"}, "avoid": {"name": "Tema India", "why": "sub-scale"}},
    "WENDT": {"set": "Super-abrasives & grinding (India)", "of": 6, "rank": 5, "action": "HOLD",
              "peers": [P("Saint-Gobain (global)", 7.8, V_STRONG), P("Grindwell Norton", 7.4, V_STRONG), P("3M India", 7.2, V_SOLID), P("Carborundum Universal", 7.0, V_SOLID), P("Wendt India", 6.4, V_SOLID, True), P("AIA Engineering (adjacent)", 7.6, V_STRONG)],
              "why": "Niche super-abrasives/diamond-tool maker with a debt-free balance sheet but very small, illiquid and earnings decline.",
              "best_own": {"name": "Grindwell Norton", "why": "scale + RoCE"}, "avoid": {"name": "Wendt India", "why": "sub-scale, illiquid"}},
    "SGIL": {"set": "Wind / heavy castings (India)", "of": 6, "rank": 5, "action": "HOLD",
             "peers": [P("AIA Engineering", 7.6, V_STRONG), P("Kirloskar Ferrous", 6.6, V_SOLID), P("Electrosteel Castings", 6.4, V_SOLID), P("Simplex Castings", 5.8, V_AVG), P("Synergy Green Industries", 5.6, V_WEAK, True), P("RACL Geartech", 6.2, V_AVG)],
             "why": "Wind-turbine heavy-casting supplier riding RE capex but high leverage, sharp PAT decline and a very high PE.",
             "best_own": {"name": "AIA Engineering", "why": "high-RoCE castings leader"}, "avoid": {"name": "Synergy Green Industries", "why": "await deleveraging"}},
    "KSB": {"set": "Industrial pumps & valves (India)", "of": 6, "rank": 3, "action": "HOLD",
            "peers": [P("Grundfos (unlisted)", 7.6, V_STRONG), P("Kirloskar Brothers", 7.2, V_SOLID), P("KSB Limited", 7.0, V_SOLID, True), P("Shakti Pumps", 7.0, V_SOLID), P("WPIL", 6.6, V_SOLID), P("Roto Pumps", 6.4, V_SOLID)],
            "why": "German-parent pumps/valves for nuclear/industrial with a clean balance sheet but a recent PAT dip and cyclicality.",
            "best_own": {"name": "Kirloskar Brothers", "why": "scale + RoCE"}, "avoid": {"name": "Roto Pumps", "why": "sub-scale"}},
    "JYOTICNC": {"set": "CNC machine tools (India + global)", "of": 6, "rank": 3, "action": "HOLD",
                 "peers": [P("DMG Mori (global)", 7.6, V_STRONG), P("Lakshmi Machine Works", 7.2, V_SOLID), P("Jyoti CNC Automation", 7.0, V_SOLID, True), P("Ace Micromatic (unlisted)", 7.0, V_SOLID), P("Bharat Fritz Werner (unlisted)", 6.6, V_SOLID), P("Macpower CNC", 6.4, V_SOLID)],
                 "why": "#1 listed Indian CNC OEM with an aero/defence order book and 18% ROE but a recent PAT dip and working-capital intensity.",
                 "best_own": {"name": "Lakshmi Machine Works", "why": "scale + balance sheet"}, "avoid": {"name": "Macpower CNC", "why": "sub-scale"}},
    "3MINDIA": {"set": "Diversified industrials / consumer (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Pidilite Industries", 8.0, V_STRONG), P("Bosch India", 7.8, V_STRONG), P("3M India", 7.6, V_STRONG, True), P("Honeywell Automation", 7.4, V_STRONG), P("SKF India", 7.4, V_STRONG), P("Grindwell Norton", 7.4, V_STRONG)],
                "why": "Parent-tech diversified portfolio with 29% ROE and strong cash but premium valuation and an MNC-royalty drag.",
                "best_own": {"name": "Pidilite Industries", "why": "brand moat + compounding"}, "avoid": {"name": "Bosch India", "why": "more cyclical auto mix"}},
    "VASCONEQ": {"set": "Real estate & EPC contracting (India)", "of": 6, "rank": 6, "action": "HOLD",
                 "peers": [P("DLF", 8.0, V_STRONG), P("Godrej Properties", 7.8, V_STRONG), P("Ahluwalia Contracts", 6.6, V_SOLID), P("PSP Projects", 6.4, V_SOLID), P("Capacit'e Infraprojects", 6.2, V_AVG), P("Vascon Engineers", 5.4, V_WEAK, True)],
                 "why": "Small RE+EPC with a Pune land bank but heavy losses, negative OCF and a weak balance sheet.",
                 "best_own": {"name": "DLF", "why": "scale + annuity portfolio"}, "avoid": {"name": "Vascon Engineers", "why": "await turnaround"}},
    "RAYMOND": {"set": "Branded textiles + real estate (India)", "of": 6, "rank": 6, "action": "HOLD",
                "peers": [P("Page Industries", 8.0, V_STRONG), P("KPR Mill", 7.4, V_STRONG), P("Vardhman Textiles", 7.2, V_SOLID), P("Arvind", 6.6, V_SOLID), P("Welspun Living", 6.2, V_AVG), P("Raymond", 6.0, V_AVG, True)],
                "why": "90-year suiting brand plus Thane land-bank value but demerger complexity, low ROE and high PE.",
                "best_own": {"name": "Page Industries", "why": "brand moat + RoCE"}, "avoid": {"name": "Raymond", "why": "low ROE until realty monetises"}},
    "RAYMONDREL": {"set": "Mumbai-region real estate (India)", "of": 6, "rank": 6, "action": "HOLD",
                   "peers": [P("Godrej Properties", 8.0, V_STRONG), P("Oberoi Realty", 7.8, V_STRONG), P("Macrotech (Lodha)", 7.6, V_STRONG), P("Sunteck Realty", 6.6, V_SOLID), P("Keystone Realtors", 6.6, V_SOLID), P("Raymond Realty", 6.4, V_SOLID, True)],
                   "why": "Thane township with irreplaceable land and the Raymond brand but single-asset concentration and early-stage execution.",
                   "best_own": {"name": "Godrej Properties", "why": "pan-India brand + execution"}, "avoid": {"name": "Sunteck Realty", "why": "lumpy launches"}},
    "RUSTOMJEE": {"set": "Mumbai-region real estate (India)", "of": 6, "rank": 5, "action": "HOLD",
                  "peers": [P("Godrej Properties", 8.0, V_STRONG), P("Oberoi Realty", 7.8, V_STRONG), P("Macrotech (Lodha)", 7.6, V_STRONG), P("Sunteck Realty", 6.6, V_SOLID), P("Keystone Realtors", 6.6, V_SOLID, True), P("Raymond Realty", 6.4, V_SOLID)],
                  "why": "Trusted MMR brand with a JDA-led asset-light model but negative OCF and intense MMR-luxury competition.",
                  "best_own": {"name": "Oberoi Realty", "why": "premium, high-RoCE"}, "avoid": {"name": "Raymond Realty", "why": "single-asset, early-stage"}},
    "ELDEHSG": {"set": "Tier-2 real estate (India)", "of": 6, "rank": 4, "action": "HOLD",
                "peers": [P("Godrej Properties", 8.0, V_STRONG), P("Anant Raj", 7.0, V_SOLID), P("Ashiana Housing", 6.8, V_SOLID), P("Eldeco Housing", 6.6, V_SOLID, True), P("Mahindra Lifespaces", 6.6, V_SOLID), P("Sunteck Realty", 6.6, V_SOLID)],
                "why": "35-year UP/Lucknow brand with an asset-light model and high growth but small and regionally concentrated.",
                "best_own": {"name": "Godrej Properties", "why": "brand + national scale"}, "avoid": {"name": "Sunteck Realty", "why": "lumpy launches"}},
    "ASHIANA": {"set": "Mid-income / senior-living RE (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("Godrej Properties", 8.0, V_STRONG), P("Brigade Enterprises", 7.2, V_SOLID), P("Ashiana Housing", 6.8, V_SOLID, True), P("Mahindra Lifespaces", 6.8, V_SOLID), P("Eldeco Housing", 6.6, V_SOLID), P("Kolte-Patil", 6.6, V_SOLID)],
                "why": "Disciplined mid-income plus senior-living first-mover with an area-sell model but small parcels and cyclicality.",
                "best_own": {"name": "Brigade Enterprises", "why": "diversified, high-RoCE"}, "avoid": {"name": "Kolte-Patil", "why": "lumpy execution"}},
    "EMBDL": {"set": "Commercial real estate (India)", "of": 6, "rank": 6, "action": "HOLD",
              "peers": [P("DLF", 8.0, V_STRONG), P("Embassy Office REIT", 7.8, V_STRONG), P("Prestige Estates", 7.4, V_STRONG), P("Brookfield India REIT", 7.2, V_SOLID), P("Mindspace REIT", 7.2, V_SOLID), P("Embassy Developments", 6.0, V_AVG, True)],
              "why": "Prime office land bank and marquee tenants but negative ROE, restructuring and execution overhang.",
              "best_own": {"name": "DLF", "why": "best annuity + balance sheet"}, "avoid": {"name": "Embassy Developments", "why": "await cash flows"}},
    "TREL": {"set": "Logistics real estate / parks (India)", "of": 6, "rank": 5, "action": "HOLD",
             "peers": [P("Embassy Office REIT", 7.8, V_STRONG), P("Mindspace REIT", 7.2, V_SOLID), P("Allcargo Logistics", 7.0, V_SOLID), P("Welspun One (unlisted)", 6.6, V_SOLID), P("Transindia Real Estate", 6.2, V_AVG, True), P("NDR InvIT", 6.0, V_AVG)],
             "why": "Allcargo-demerged logistics-park plus engineering-solutions play but small, lumpy and early-stage.",
             "best_own": {"name": "Embassy Office REIT", "why": "scale + yield"}, "avoid": {"name": "NDR InvIT", "why": "narrow, early"}},
    "OMINFRAL": {"set": "Hydro / water-infra EPC (India)", "of": 6, "rank": 5, "action": "HOLD",
                 "peers": [P("Larsen & Toubro", 8.0, V_STRONG), P("NCC", 7.0, V_SOLID), P("J Kumar Infraprojects", 6.8, V_SOLID), P("Patel Engineering", 6.6, V_SOLID), P("Om Infra", 5.8, V_AVG, True), P("HCC", 5.5, V_WEAK)],
                 "why": "Dam/hydro EPC plus toll and SRA realty optionality but lumpy projects, negative OCF and losses.",
                 "best_own": {"name": "Larsen & Toubro", "why": "execution + balance sheet"}, "avoid": {"name": "HCC", "why": "debt-laden"}},
    "INTERARCH": {"set": "Pre-engineered buildings (India)", "of": 6, "rank": 3, "action": "HOLD",
                  "peers": [P("Tata BlueScope (unlisted)", 7.2, V_SOLID), P("Pennar Industries", 7.0, V_SOLID), P("Interarch Building", 7.0, V_SOLID, True), P("Kirby (unlisted)", 6.8, V_SOLID), P("Everest Industries", 6.4, V_SOLID), P("Smith Structures", 6.0, V_AVG)],
                  "why": "#2 PEB maker with in-house design and an e-commerce-warehouse tailwind but steel-price margins and a weak OCF quarter.",
                  "best_own": {"name": "Tata BlueScope (unlisted)", "why": "scale + steel integration"}, "avoid": {"name": "Smith Structures", "why": "sub-scale"}},
    "CAPACITE": {"set": "Building construction contractors (India)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("Larsen & Toubro", 8.0, V_STRONG), P("NCC", 7.0, V_SOLID), P("Ahluwalia Contracts", 7.0, V_SOLID), P("Capacit'e Infraprojects", 6.6, V_SOLID, True), P("PSP Projects", 6.6, V_SOLID), P("J Kumar Infraprojects", 6.6, V_SOLID)],
                 "why": "Mivan-formwork high-rise specialist for tier-1 developers but developer-credit risk and a working-capital-heavy model.",
                 "best_own": {"name": "Larsen & Toubro", "why": "execution + diversification"}, "avoid": {"name": "J Kumar Infraprojects", "why": "leverage, lumpy"}},
    "ARIS": {"set": "B2B construction-materials marketplace (India)", "of": 6, "rank": 6, "action": "HOLD",
             "peers": [P("OfBusiness (unlisted)", 7.6, V_STRONG), P("Infra.Market (unlisted)", 7.4, V_STRONG), P("Moglix (unlisted)", 6.8, V_SOLID), P("Shankara Building Products", 6.4, V_SOLID), P("Bizongo (unlisted)", 6.0, V_AVG), P("Arisinfra Solutions", 5.6, V_WEAK, True)],
             "why": "Tech-enabled construction-materials marketplace but loss-making, thin margins and working-capital-heavy vs better-funded peers.",
             "best_own": {"name": "OfBusiness (unlisted)", "why": "profitable, financing-led"}, "avoid": {"name": "Arisinfra Solutions", "why": "await profitability"}},
    "SHANKARA": {"set": "Building-materials retail (India)", "of": 6, "rank": 4, "action": "HOLD",
                 "peers": [P("OfBusiness (unlisted)", 7.6, V_STRONG), P("Infra.Market (unlisted)", 7.4, V_STRONG), P("Moglix (unlisted)", 6.8, V_SOLID), P("Shankara Building Products", 6.2, V_AVG, True), P("Bizongo (unlisted)", 6.0, V_AVG), P("Arisinfra Solutions", 5.6, V_WEAK)],
                 "why": "South-India multi-brand building-materials retail with a store network but very low ROE, negative OCF and steel-price swings.",
                 "best_own": {"name": "Infra.Market (unlisted)", "why": "scale + own brands"}, "avoid": {"name": "Arisinfra Solutions", "why": "loss-making"}},
    "WHIRLPOOL": {"set": "Consumer appliances (India)", "of": 6, "rank": 6, "action": "HOLD",
                  "peers": [P("Havells India", 7.8, V_STRONG), P("Voltas", 7.4, V_STRONG), P("Blue Star", 7.2, V_SOLID), P("Crompton Greaves Consumer", 6.8, V_SOLID), P("Symphony", 6.6, V_SOLID), P("Whirlpool of India", 6.2, V_AVG, True)],
                  "why": "Global-parent tech and washing-machine strength but losing share to Samsung/LG, declining PAT and a promoter sell-down.",
                  "best_own": {"name": "Havells India", "why": "brand + capital allocation"}, "avoid": {"name": "Whirlpool of India", "why": "await share stabilisation"}},
    "ABLBL": {"set": "Branded apparel retail (India)", "of": 6, "rank": 5, "action": "HOLD",
              "peers": [P("Trent", 8.2, V_STRONG), P("Page Industries", 8.0, V_STRONG), P("Go Fashion", 7.0, V_SOLID), P("Raymond Lifestyle", 6.8, V_SOLID), P("Aditya Birla Lifestyle", 6.6, V_SOLID, True), P("Arvind Fashions", 6.4, V_SOLID)],
              "why": "Premium apparel brands and retail scale post-demerger but high leverage, markdown risk and a discretionary slowdown.",
              "best_own": {"name": "Trent", "why": "fast-fashion compounding"}, "avoid": {"name": "Arvind Fashions", "why": "leveraged, mixed brands"}},
    "BOROLTD": {"set": "Consumer glassware / kitchenware (India)", "of": 6, "rank": 5, "action": "HOLD",
                "peers": [P("Hawkins Cookers", 7.4, V_STRONG), P("TTK Prestige", 7.2, V_SOLID), P("La Opala RG", 7.0, V_SOLID), P("Cello World", 6.8, V_SOLID), P("Borosil", 6.6, V_SOLID, True), P("Stove Kraft", 6.0, V_AVG)],
                "why": "Trusted borosilicate brand with capacity-led growth but low ROE and energy-cost-driven margins.",
                "best_own": {"name": "TTK Prestige", "why": "brand + distribution"}, "avoid": {"name": "Stove Kraft", "why": "thin, competitive"}},
    "ORIENTHOT": {"set": "Hotels (India)", "of": 6, "rank": 5, "action": "HOLD",
                  "peers": [P("Indian Hotels (IHCL)", 8.2, V_STRONG), P("EIH (Oberoi)", 8.0, V_STRONG), P("Chalet Hotels", 7.4, V_STRONG), P("Lemon Tree Hotels", 7.0, V_SOLID), P("Oriental Hotels", 6.4, V_SOLID, True), P("SAMHI Hotels", 6.2, V_AVG)],
                  "why": "Taj-affiliated premium South-India assets with ADR upside but regional concentration and lower scale.",
                  "best_own": {"name": "Indian Hotels (IHCL)", "why": "brand + pipeline + RoCE"}, "avoid": {"name": "SAMHI Hotels", "why": "leveraged roll-up"}},
    "EIHOTEL": {"set": "Luxury hotels (India)", "of": 6, "rank": 2, "action": "HOLD",
                "peers": [P("Indian Hotels (IHCL)", 8.2, V_STRONG), P("EIH (Oberoi)", 8.0, V_STRONG, True), P("ITC Hotels", 7.6, V_STRONG), P("Chalet Hotels", 7.4, V_STRONG), P("Lemon Tree Hotels", 7.0, V_SOLID), P("Juniper Hotels", 6.6, V_SOLID)],
                "why": "Oberoi/Trident — the cleanest luxury brand moat with irreplaceable assets and 9/10 pricing power; behind IHCL only on scale/pipeline.",
                "best_own": {"name": "Indian Hotels (IHCL)", "why": "scale + asset-light pipeline"}, "avoid": {"name": "Juniper Hotels", "why": "leveraged, concentrated"}},
    "MSTCLTD": {"set": "E-commerce / e-auction PSUs (India)", "of": 6, "rank": 3, "action": "HOLD",
                "peers": [P("IRCTC", 7.6, V_STRONG), P("RITES", 7.0, V_SOLID), P("MSTC", 6.8, V_SOLID, True), P("mjunction (unlisted)", 6.6, V_SOLID), P("IRCON International", 6.6, V_SOLID), P("MMTC", 5.8, V_AVG)],
                "why": "Trusted government e-auction franchise with 26% ROE and a high dividend but policy-linked volumes and ferrous-scrap exposure.",
                "best_own": {"name": "IRCTC", "why": "captive monopoly + cash"}, "avoid": {"name": "MMTC", "why": "weak trading model"}},
    "INCAP": {"set": "Electronic components (small-cap India)", "of": 6, "rank": 6, "action": "HOLD",
              "peers": [P("Kaynes Technology", 7.6, V_STRONG), P("Syrma SGS", 6.8, V_SOLID), P("PG Electroplast", 6.4, V_SOLID), P("Avalon Technologies", 6.3, V_SOLID), P("SPEL Semiconductor", 5.2, V_WEAK), P("Incap", 5.0, V_WEAK, True)],
              "why": "Micro-cap with unverified positioning, a very high PE and weak returns — lowest-quality in the set (low confidence).",
              "best_own": {"name": "Kaynes Technology", "why": "scale + execution"}, "avoid": {"name": "Incap", "why": "sub-scale, pending verification"}},
}

# normalize: sort each peer list by score (desc, stable) and recompute rank/of
for _k, _v in DATA.items():
    if _k == "_meta":
        continue
    _v["peers"].sort(key=lambda p: -p.get("score", 0))
    _v["of"] = len(_v["peers"])
    _si = next((i for i, p in enumerate(_v["peers"]) if p.get("self")), None)
    if _si is not None:
        _v["rank"] = _si + 1

json.dump(DATA, open(OUT, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
n = len([k for k in DATA if k != "_meta"])
print(f"wrote peer_rank.json with {n} real-peer verdicts")
